
require 'rubygems'
require 'ffi'

module ActiveworldsFFI
  extend FFI::Library
  ffi_lib "libstdc++.so.6"
  ffi_lib "libaw_sdk.42.so"
  
  # Reason Codes
  RC_SUCCESS = 0
  RC_CITIZENSHIP_EXPIRED = 1
  RC_LAND_LIMIT_EXCEEDED = 2
  RC_NO_SUCH_CITIZEN = 3
  RC_MESSAGE_LENGTH_BAD = 4
  RC_LICENSE_PASSWORD_CONTAINS_SPACE = 5
  RC_LICENSE_PASSWORD_TOO_LONG = 6
  RC_LICENSE_PASSWORD_TOO_SHORT = 7
  RC_LICENSE_RANGE_TOO_LARGE = 8
  RC_LICENSE_RANGE_TOO_SMALL = 9
  RC_LICENSE_USERS_TOO_LARGE = 10
  RC_LICENSE_USERS_TOO_SMALL = 11
  RC_LICENSE_CONTAINS_INVALID_CHAR = 12
  RC_INVALID_PASSWORD = 13
  RC_UNABLE_TO_MAIL_BACK_NUMBER = 14
  RC_LICENSE_WORLD_TOO_SHORT = 15
  RC_LICENSE_WORLD_TOO_LONG = 16
  RC_SERVER_OUT_OF_MEMORY = 17
  RC_INVALID_WORLD = 20
  RC_SERVER_OUTDATED = 21
  RC_WORLD_ALREADY_STARTED = 22
  RC_NO_SUCH_WORLD = 27
  RC_NOT_LOGGED_IN = 31
  RC_UNAUTHORIZED = 32
  RC_WORLD_ALREADY_EXISTS = 33
  RC_NO_SUCH_LICENSE = 34
  RC_IDENTITY_ALREADY_IN_USE = 39
  RC_UNABLE_TO_REPORT_LOCATION = 40
  RC_INVALID_EMAIL = 41
  RC_NO_SUCH_ACTING_CITIZEN = 42
  RC_ACTING_PASSWORD_INVALID = 43
  RC_UNIVERSE_FULL = 45
  RC_BILLING_TIMEOUT = 46
  RC_BILLING_RECV_FAILED = 47
  RC_BILLING_RESPONSE_INVALID = 48
  RC_BILLING_REJECTED = 55
  RC_BILLING_BLOCKED = 56
  RC_TOO_MANY_WORLDS = 57
  RC_MUST_UPGRADE = 58
  RC_BOT_LIMIT_EXCEEDED = 59
  RC_WORLD_EXPIRED = 61
  RC_CITIZEN_DOES_NOT_EXPIRE = 62
  RC_LICENSE_STARTS_WITH_NUMBER = 64
  RC_NO_SUCH_EJECTION = 66
  RC_NO_SUCH_SESSION = 67
  RC_EJECTION_EXPIRED = 69
  RC_ACTING_CITIZEN_EXPIRED = 70
  RC_ALREADY_STARTED = 71
  RC_WORLD_RUNNING = 72
  RC_WORLD_NOT_SET = 73
  RC_NO_SUCH_CELL = 74
  RC_NO_REGISTRY = 75
  RC_CANT_OPEN_REGISTRY = 76
  RC_CITIZEN_DISABLED = 77
  RC_WORLD_DISABLED = 78
  RC_BETA_REQUIRED = 79
  RC_ACTING_CITIZEN_DISABLED = 80
  RC_INVALID_USER_COUNT = 81
  RC_PRIVATE_WORLD = 91
  RC_NO_TOURISTS = 92
  RC_EMAIL_CONTAINS_INVALID_CHAR = 100
  RC_EMAIL_ENDS_WITH_BLANK = 101
  RC_NO_SUCH_OBJECT = 101
  RC_EMAIL_MISSING_DOT = 102
  RC_NOT_DELETE_OWNER = 102
  RC_EMAIL_MISSING_AT = 103
  RC_EMAIL_STARTS_WITH_BLANK = 104
  RC_EMAIL_TOO_LONG = 105
  RC_EMAIL_TOO_SHORT = 106
  RC_NAME_ALREADY_USED = 107
  RC_NAME_CONTAINS_NONALPHANUMERIC_CHAR = 108
  RC_NAME_CONTAINS_INVALID_BLANK = 109
  RC_NAME_DOESNT_EXIST = 110
  RC_NAME_ENDS_WITH_BLANK = 111
  RC_NAME_TOO_LONG = 112
  RC_NAME_TOO_SHORT = 113
  RC_NAME_UNUSED = 114
  RC_PASSWORD_TOO_LONG = 115
  RC_PASSWORD_TOO_SHORT = 116
  RC_PASSWORD_WRONG = 117
  RC_UNABLE_TO_DELETE_NAME = 119
  RC_UNABLE_TO_GET_CITIZEN = 120
  RC_UNABLE_TO_INSERT_CITIZEN = 121
  RC_UNABLE_TO_INSERT_NAME = 122
  RC_UNABLE_TO_PUT_CITIZEN_COUNT = 123
  RC_UNABLE_TO_DELETE_CITIZEN = 124
  RC_NUMBER_ALREADY_USED = 126
  RC_NUMBER_OUT_OF_RANGE = 127
  RC_PRIVILEGE_PASSWORD_IS_TOO_SHORT = 128
  RC_PRIVILEGE_PASSWORD_IS_TOO_LONG = 129
  RC_NOT_CHANGE_OWNER = 203
  RC_CANT_FIND_OLD_ELEMENT = 204
  RC_UNABLE_TO_CHANGE_ATTRIBUTE = 210
  RC_CANT_CHANGE_OWNER = 211
  RC_IMPOSTER = 212
  RC_INVALID_REQUEST = 213
  RC_CANT_BUILD_HERE = 216
  RC_ENCROACHES = 300
  RC_OBJECT_TYPE_INVALID = 301
  RC_TOO_MANY_BYTES = 303
  RC_UNABLE_TO_STORE = 305
  RC_UNREGISTERED_OBJECT = 306
  RC_ELEMENT_ALREADY_EXISTS = 308
  RC_RESTRICTED_COMMAND = 309
  RC_NO_BUILD_RIGHTS = 310
  RC_OUT_OF_BOUNDS = 311
  RC_RESTRICTED_OBJECT = 313
  RC_RESTRICTED_AREA = 314
  RC_OUT_OF_MEMORY = 400
  RC_NOT_YET = 401
  RC_TIMEOUT = 402
  RC_NULL_POINTER = 403
  RC_UNABLE_TO_CONTACT_UNIVERSE = 404
  RC_UNABLE_TO_CONTACT_WORLD = 405
  RC_INVALID_WORLD_NAME = 406
  RC_SEND_FAILED = 415
  RC_RECEIVE_FAILED = 416
  RC_STREAM_EMPTY = 421
  RC_STREAM_MESSAGE_TOO_LONG = 422
  RC_WORLD_NAME_TOO_LONG = 423
  RC_MESSAGE_TOO_LONG = 426
  RC_TOO_MANY_RESETS = 427
  RC_UNABLE_TO_CREATE_SOCKET = 428
  RC_UNABLE_TO_CONNECT = 429
  RC_UNABLE_TO_SET_NONBLOCKING = 430
  RC_CANT_OPEN_STREAM = 434
  RC_CANT_WRITE_STREAM = 435
  RC_CANT_CLOSE_STREAM = 436
  RC_NO_CONNECTION = 439
  RC_UNABLE_TO_INITIALIZE_NETWORK = 442
  RC_INCORRECT_MESSAGE_LENGTH = 443
  RC_NOT_INITIALIZED = 444
  RC_NO_INSTANCE = 445
  RC_OUT_BUFFER_FULL = 446
  RC_INVALID_CALLBACK = 447
  RC_INVALID_ATTRIBUTE = 448
  RC_TYPE_MISMATCH = 449
  RC_STRING_TOO_LONG = 450
  RC_READ_ONLY = 451
  RC_UNABLE_TO_REGISTER_RESOLVE = 452
  RC_INVALID_INSTANCE = 453
  RC_VERSION_MISMATCH = 454
  RC_IN_BUFFER_FULL = 461
  RC_PROTOCOL_ERROR = 463
  RC_QUERY_IN_PROGRESS = 464
  RC_WORLD_FULL = 465
  RC_EJECTED = 466
  RC_NOT_WELCOME = 467
  RC_UNABLE_TO_BIND = 468
  RC_UNABLE_TO_LISTEN = 469
  RC_UNABLE_TO_ACCEPT = 470
  RC_CONNECTION_LOST = 471
  RC_NO_STREAM = 473
  RC_NOT_AVAILABLE = 474
  RC_OLD_UNIVERSE = 487
  RC_OLD_WORLD = 488
  RC_WORLD_NOT_RUNNING = 489
  RC_CANT_RESOLVE_UNIVERSE_HOST = 500
  RC_INVALID_ARGUMENT = 505
  RC_WORLD_INSTANCE_ALREADY_EXISTS = 521
  RC_WORLD_INSTANCE_INVALID = 522
  RC_EMAIL_CHANGE_NOT_ALLOWED = 525
  RC_NAME_CHANGE_NOT_ALLOWED = 526
  RC_EMAIL_ALREADY_USED = 527
  RC_EMAIL_NOT_ALLOWED = 528
  RC_WORLD_REDIRECT = 529
  RC_DATABASE_ERROR = 600
  
  # beginning of standard Aw.h
  AW_BUILD = 77
  AW_MAX_AVCHANGE_PER_SECOND = 10
  AW_MAX_MESSAGES_PER_SECOND = 100
  AW_MAX_WHISPERS_PER_SECOND = 100
  AW_MAX_BOTGRAMS_PER_SECOND = 32
  AW_MAX_ATTRIBUTE_LENGTH = 255
  AW_CELL_MIN = -32767
  AW_PERSONAL_AVATAR = 65535
  AW_CUSTOM_AVATAR = 65534
  AW_CUSTOM_WORLD_AVATAR = 65533
  AW_OBJECT_VERSION_CAMERA = 1
  AW_OBJECT_VERSION_PARTICLES = 1
  AW_OBJECT_VERSION_ZONE = 1
  AW_OBJECT_VERSION_MOVER = 1
  AW_LOGIN_NAME = 0
  AW_LOGIN_PASSWORD = 1
  AW_UNIVERSE_BROWSER_BETA = 10
  AW_WORLD_SKYBOX = 100
  AW_WORLD_MINIMUM_VISIBILITY = 101
  AW_WORLD_REPEATING_GROUND = 102
  AW_WORLD_KEYWORDS = 103
  AW_WORLD_ENABLE_TERRAIN = 104
  AW_WORLD_ALLOW_3_AXIS_ROTATION = 105
  AW_WORLD_TERRAIN_TIMESTAMP = 106
  AW_WORLD_ENTRY_POINT = 107
  AW_WORLD_SKY_NORTH_RED = 108
  AW_WORLD_SKY_NORTH_GREEN = 109
  AW_UNIVERSE_WORLD_MINIMUM = 11
  AW_WORLD_SKY_NORTH_BLUE = 110
  AW_WORLD_SKY_SOUTH_RED = 111
  AW_WORLD_SKY_SOUTH_GREEN = 112
  AW_WORLD_SKY_SOUTH_BLUE = 113
  AW_WORLD_SKY_EAST_RED = 114
  AW_WORLD_SKY_EAST_GREEN = 115
  AW_WORLD_SKY_EAST_BLUE = 116
  AW_WORLD_SKY_WEST_RED = 117
  AW_WORLD_SKY_WEST_GREEN = 118
  AW_WORLD_SKY_WEST_BLUE = 119
  AW_UNIVERSE_WORLD_START = 12
  AW_WORLD_SKY_TOP_RED = 120
  AW_WORLD_SKY_TOP_GREEN = 121
  AW_WORLD_SKY_TOP_BLUE = 122
  AW_WORLD_SKY_BOTTOM_RED = 123
  AW_WORLD_SKY_BOTTOM_GREEN = 124
  AW_WORLD_SKY_BOTTOM_BLUE = 125
  AW_WORLD_CLOUDS_LAYER1_TEXTURE = 126
  AW_WORLD_CLOUDS_LAYER1_MASK = 127
  AW_WORLD_CLOUDS_LAYER1_TILE = 128
  AW_WORLD_CLOUDS_LAYER1_SPEED_X = 129
  AW_UNIVERSE_REGISTRATION_REQUIRED = 13
  AW_WORLD_CLOUDS_LAYER1_SPEED_Z = 130
  AW_WORLD_CLOUDS_LAYER1_OPACITY = 131
  AW_WORLD_CLOUDS_LAYER2_TEXTURE = 132
  AW_WORLD_CLOUDS_LAYER2_MASK = 133
  AW_WORLD_CLOUDS_LAYER2_TILE = 134
  AW_WORLD_CLOUDS_LAYER2_SPEED_X = 135
  AW_WORLD_CLOUDS_LAYER2_SPEED_Z = 136
  AW_WORLD_CLOUDS_LAYER2_OPACITY = 137
  AW_WORLD_CLOUDS_LAYER3_TEXTURE = 138
  AW_WORLD_CLOUDS_LAYER3_MASK = 139
  AW_UNIVERSE_BUILD_NUMBER = 14
  AW_WORLD_CLOUDS_LAYER3_TILE = 140
  AW_WORLD_CLOUDS_LAYER3_SPEED_X = 141
  AW_WORLD_CLOUDS_LAYER3_SPEED_Z = 142
  AW_WORLD_CLOUDS_LAYER3_OPACITY = 143
  AW_WORLD_DISABLE_CHAT = 144
  AW_WORLD_ALLOW_CITIZEN_WHISPER = 145
  AW_WORLD_ALWAYS_SHOW_NAMES = 146
  AW_WORLD_DISABLE_AVATAR_LIST = 147
  AW_WORLD_AVATAR_REFRESH_RATE = 148
  AW_WORLD_WATER_TEXTURE = 149
  AW_UNIVERSE_MONTHLY_CHARGE = 15
  AW_WORLD_WATER_MASK = 150
  AW_WORLD_WATER_BOTTOM_TEXTURE = 151
  AW_WORLD_WATER_BOTTOM_MASK = 152
  AW_WORLD_WATER_OPACITY = 153
  AW_WORLD_WATER_RED = 154
  AW_WORLD_WATER_GREEN = 155
  AW_WORLD_WATER_BLUE = 156
  AW_WORLD_WATER_LEVEL = 157
  AW_WORLD_WATER_SURFACE_MOVE = 158
  AW_WORLD_WATER_WAVE_MOVE = 159
  AW_UNIVERSE_ANNUAL_CHARGE = 16
  AW_WORLD_WATER_SPEED = 160
  AW_WORLD_WATER_ENABLED = 161
  AW_WORLD_EMINENT_DOMAIN_CAPABILITY = 162
  AW_WORLD_LIGHT_TEXTURE = 163
  AW_WORLD_LIGHT_MASK = 164
  AW_WORLD_LIGHT_DRAW_SIZE = 165
  AW_WORLD_LIGHT_DRAW_FRONT = 166
  AW_WORLD_LIGHT_DRAW_BRIGHT = 167
  AW_WORLD_LIGHT_SOURCE_USE_COLOR = 168
  AW_WORLD_LIGHT_SOURCE_COLOR = 169
  AW_UNIVERSE_REGISTER_METHOD = 17
  AW_WORLD_TERRAIN_AMBIENT = 170
  AW_WORLD_TERRAIN_DIFFUSE = 171
  AW_WORLD_WATER_VISIBILITY = 172
  AW_WORLD_SOUND_FOOTSTEP = 173
  AW_WORLD_SOUND_WATER_ENTER = 174
  AW_WORLD_SOUND_WATER_EXIT = 175
  AW_WORLD_SOUND_AMBIENT = 176
  AW_WORLD_GRAVITY = 177
  AW_WORLD_BUOYANCY = 178
  AW_WORLD_FRICTION = 179
  AW_UNIVERSE_TIME = 18
  AW_WORLD_WATER_FRICTION = 180
  AW_WORLD_SLOPESLIDE_ENABLED = 181
  AW_WORLD_SLOPESLIDE_MIN_ANGLE = 182
  AW_WORLD_SLOPESLIDE_MAX_ANGLE = 183
  AW_WORLD_ALLOW_TOURIST_BUILD = 184
  AW_WORLD_ENABLE_REFERER = 185
  AW_WORLD_WATER_UNDER_TERRAIN = 186
  AW_WORLD_TERRAIN_OFFSET = 187
  AW_WORLD_VOIP_RIGHT = 188
  AW_WORLD_DISABLE_MULTIPLE_MEDIA = 189
  AW_UNIVERSE_CITIZEN_CHANGES_ALLOWED = 19
  AW_WORLD_BOTMENU_URL = 190
  AW_WORLD_ENABLE_BUMP_EVENT = 191
  AW_WORLD_ENABLE_SYNC_EVENTS = 192
  AW_WORLD_ENABLE_CAV = 193
  AW_WORLD_ENABLE_PAV = 194
  AW_WORLD_CHAT_DISABLE_URL_CLICKS = 195
  AW_WORLD_MOVER_EMPTY_RESET_TIMEOUT = 196
  AW_WORLD_MOVER_USED_RESET_TIMEOUT = 197
  AW_MY_X = 198
  AW_MY_Y = 199
  AW_LOGIN_OWNER = 2
  AW_UNIVERSE_BROWSER_RELEASE_22 = 20
  AW_MY_Z = 200
  AW_MY_YAW = 201
  AW_MY_PITCH = 202
  AW_MY_TYPE = 203
  AW_MY_GESTURE = 204
  AW_MY_STATE = 205
  AW_AVATAR_SESSION = 206
  AW_AVATAR_NAME = 207
  AW_AVATAR_X = 208
  AW_AVATAR_Y = 209
  AW_UNIVERSE_WELCOME_MESSAGE = 21
  AW_AVATAR_Z = 210
  AW_AVATAR_YAW = 211
  AW_AVATAR_PITCH = 212
  AW_AVATAR_TYPE = 213
  AW_AVATAR_GESTURE = 214
  AW_AVATAR_STATE = 215
  AW_AVATAR_ADDRESS = 216
  AW_AVATAR_VERSION = 217
  AW_AVATAR_CITIZEN = 218
  AW_AVATAR_PRIVILEGE = 219
  AW_UNIVERSE_WORLD_RELEASE = 22
  AW_AVATAR_LOCK = 220
  AW_AVATAR_FLAGS = 221
  AW_CHAT_SESSION = 222
  AW_CHAT_MESSAGE = 223
  AW_CELL_X = 224
  AW_CELL_Z = 225
  AW_CELL_SEQUENCE = 226
  AW_CELL_SIZE = 227
  AW_CELL_ITERATOR = 228
  AW_CELL_COMBINE = 229
  AW_UNIVERSE_WORLD_BETA = 23
  AW_OBJECT_ID = 230
  AW_OBJECT_NUMBER = 231
  AW_OBJECT_X = 232
  AW_OBJECT_Y = 233
  AW_OBJECT_Z = 234
  AW_OBJECT_YAW = 235
  AW_OBJECT_TILT = 236
  AW_OBJECT_ROLL = 237
  AW_OBJECT_MODEL = 238
  AW_OBJECT_DESCRIPTION = 239
  AW_UNIVERSE_ALLOW_TOURISTS = 24
  AW_OBJECT_ACTION = 240
  AW_OBJECT_OLD_NUMBER = 241
  AW_OBJECT_OLD_X = 242
  AW_OBJECT_OLD_Z = 243
  AW_OBJECT_OWNER = 244
  AW_OBJECT_SESSION = 245
  AW_OBJECT_BUILD_TIMESTAMP = 246
  AW_OBJECT_SYNC = 247
  AW_OBJECT_TYPE = 248
  AW_OBJECT_DATA = 249
  AW_UNIVERSE_SEARCH_URL = 25
  AW_QUERY_COMPLETE = 250
  AW_CHAT_TYPE = 251
  AW_LICENSE_NAME = 252
  AW_LICENSE_PASSWORD = 253
  AW_LICENSE_USERS = 254
  AW_LICENSE_RANGE = 255
  AW_LICENSE_EMAIL = 256
  AW_LICENSE_COMMENT = 257
  AW_LICENSE_CREATION_TIME = 258
  AW_LICENSE_EXPIRATION_TIME = 259
  AW_UNIVERSE_NOTEPAD_URL = 26
  AW_LICENSE_LAST_START = 260
  AW_LICENSE_LAST_ADDRESS = 261
  AW_LICENSE_HIDDEN = 262
  AW_LICENSE_ALLOW_TOURISTS = 263
  AW_LICENSE_VOIP = 264
  AW_LICENSE_PLUGINS = 265
  AW_WORLDLIST_NAME = 266
  AW_WORLDLIST_STATUS = 267
  AW_WORLDLIST_USERS = 268
  AW_WORLDLIST_RATING = 269
  AW_UNIVERSE_NAME = 27
  AW_WORLDLIST_MORE = 270
  AW_EJECT_SESSION = 271
  AW_EJECT_DURATION = 272
  AW_EJECTION_TYPE = 273
  AW_EJECTION_ADDRESS = 274
  AW_EJECTION_EXPIRATION_TIME = 275
  AW_EJECTION_CREATION_TIME = 276
  AW_EJECTION_COMMENT = 277
  AW_DISCONNECT_REASON = 278
  AW_FILE_RECIPIENT = 279
  AW_UNIVERSE_USER_LIST_ENABLED = 28
  AW_FILE_SENDER = 280
  AW_FILE_SENDER_NAME = 281
  AW_FILE_SESSION = 282
  AW_FILE_ADDRESS = 283
  AW_FILE_PORT = 284
  AW_CLICKED_SESSION = 285
  AW_CLICKED_NAME = 286
  AW_URL_NAME = 287
  AW_URL_POST = 288
  AW_URL_TARGET = 289
  AW_CITIZEN_NUMBER = 29
  AW_URL_TARGET_3D = 290
  AW_TELEPORT_WORLD = 291
  AW_TELEPORT_X = 292
  AW_TELEPORT_Y = 293
  AW_TELEPORT_Z = 294
  AW_TELEPORT_YAW = 295
  AW_TELEPORT_WARP = 296
  AW_SERVER_BUILD = 297
  AW_SERVER_NAME = 298
  AW_SERVER_PASSWORD = 299
  AW_LOGIN_PRIVILEGE_PASSWORD = 3
  AW_CITIZEN_NAME = 30
  AW_SERVER_REGISTRY = 300
  AW_SERVER_CARETAKERS = 301
  AW_SERVER_ID = 302
  AW_SERVER_INSTANCE = 303
  AW_SERVER_ENABLED = 304
  AW_SERVER_STATE = 305
  AW_SERVER_USERS = 306
  AW_SERVER_MAX_USERS = 307
  AW_SERVER_OBJECTS = 308
  AW_SERVER_SIZE = 309
  AW_CITIZEN_PASSWORD = 31
  AW_SERVER_EXPIRATION = 310
  AW_SERVER_START_RC = 311
  AW_SERVER_MORE = 312
  AW_SERVER_TERRAIN_NODES = 313
  AW_TERRAIN_X = 314
  AW_TERRAIN_Z = 315
  AW_TERRAIN_PAGE_X = 316
  AW_TERRAIN_PAGE_Z = 317
  AW_TERRAIN_NODE_X = 318
  AW_TERRAIN_NODE_Z = 319
  AW_CITIZEN_EMAIL = 32
  AW_TERRAIN_NODE_SIZE = 320
  AW_TERRAIN_NODE_TEXTURE_COUNT = 321
  AW_TERRAIN_NODE_HEIGHT_COUNT = 322
  AW_TERRAIN_NODE_TEXTURES = 323
  AW_TERRAIN_NODE_HEIGHTS = 324
  AW_TERRAIN_SEQUENCE = 325
  AW_TERRAIN_COMPLETE = 326
  AW_TERRAIN_VERSION_NEEDED = 327
  AW_ENTER_GLOBAL = 328
  AW_CONSOLE_RED = 329
  AW_CITIZEN_TIME_LEFT = 33
  AW_CONSOLE_GREEN = 330
  AW_CONSOLE_BLUE = 331
  AW_CONSOLE_BOLD = 332
  AW_CONSOLE_ITALICS = 333
  AW_CONSOLE_MESSAGE = 334
  AW_BOTGRAM_TO = 335
  AW_BOTGRAM_FROM = 336
  AW_BOTGRAM_FROM_NAME = 337
  AW_BOTGRAM_TYPE = 338
  AW_BOTGRAM_TEXT = 339
  AW_CITIZEN_PRIVILEGE_PASSWORD = 34
  AW_TOOLBAR_ID = 340
  AW_TOOLBAR_SESSION = 341
  AW_USERLIST_MORE = 342
  AW_USERLIST_NAME = 343
  AW_USERLIST_WORLD = 344
  AW_USERLIST_EMAIL = 345
  AW_USERLIST_CITIZEN = 346
  AW_USERLIST_PRIVILEGE = 347
  AW_USERLIST_STATE = 348
  AW_USERLIST_ADDRESS = 349
  AW_CITIZEN_IMMIGRATION_TIME = 35
  AW_USERLIST_ID = 350
  AW_SOUND_NAME = 351
  AW_CAMERA_LOCATION_TYPE = 352
  AW_CAMERA_LOCATION_OBJECT = 353
  AW_CAMERA_LOCATION_SESSION = 354
  AW_CAMERA_TARGET_TYPE = 355
  AW_CAMERA_TARGET_OBJECT = 356
  AW_CAMERA_TARGET_SESSION = 357
  AW_PLUGIN_STRING = 358
  AW_BOTMENU_TO_SESSION = 359
  AW_CITIZEN_EXPIRATION_TIME = 36
  AW_BOTMENU_FROM_NAME = 360
  AW_BOTMENU_FROM_SESSION = 361
  AW_BOTMENU_QUESTION = 362
  AW_BOTMENU_ANSWER = 363
  AW_CONTACT_NUMBER = 364
  AW_CONTACT_STATUS = 365
  AW_CONTACT_NAME = 366
  AW_CONTACT_WORLD = 367
  AW_CONTACT_MORE = 368
  AW_CONTACT_OPTIONS = 369
  AW_CITIZEN_BETA = 37
  AW_TELEGRAM_TO = 370
  AW_TELEGRAM_FROM = 371
  AW_TELEGRAM_TEXT = 372
  AW_TELEGRAM_SENT = 373
  AW_TELEGRAM_MORE = 374
  AW_JOIN_NAME = 375
  AW_JOIN_CITIZEN = 376
  AW_JOIN_WORLD = 377
  AW_JOIN_X = 378
  AW_JOIN_Y = 379
  AW_CITIZEN_LAST_LOGIN = 38
  AW_JOIN_Z = 380
  AW_JOIN_YAW = 381
  AW_REGISTER_CC_NAME = 382
  AW_REGISTER_CC_NUMBER = 383
  AW_REGISTER_CC_MONTH = 384
  AW_REGISTER_CC_YEAR = 385
  AW_REGISTER_ADDRESS = 386
  AW_REGISTER_CITY = 387
  AW_REGISTER_STATE = 388
  AW_REGISTER_ZIP = 389
  AW_CITIZEN_BOT_LIMIT = 39
  AW_REGISTER_PHONE_NUMBER = 390
  AW_REGISTER_BUSINESS_NAME = 391
  AW_REGISTER_VENDOR = 392
  AW_REGISTER_RESULT = 393
  AW_REGISTER_METHOD = 394
  AW_VOIP_DATA = 395
  AW_UNIVERSE_CAV_PATH = 396
  AW_CITIZEN_PAV_ENABLED = 397
  AW_CAV_CITIZEN = 398
  AW_CAV_DEFINITION = 399
  AW_LOGIN_PRIVILEGE_NUMBER = 4
  AW_CITIZEN_TOTAL_TIME = 40
  AW_ENTITY_TYPE = 400
  AW_ENTITY_ID = 401
  AW_ENTITY_STATE = 402
  AW_ENTITY_FLAGS = 403
  AW_ENTITY_X = 404
  AW_ENTITY_Y = 405
  AW_ENTITY_Z = 406
  AW_ENTITY_YAW = 407
  AW_ENTITY_PITCH = 408
  AW_ENTITY_ROLL = 409
  AW_CITIZEN_ENABLED = 41
  AW_ENTITY_OWNER_SESSION = 410
  AW_ENTITY_OWNER_CITIZEN = 411
  AW_AVATAR_DISTANCE = 412
  AW_AVATAR_ANGLE = 413
  AW_AVATAR_Y_DELTA = 414
  AW_AVATAR_YAW_DELTA = 415
  AW_AVATAR_PITCH_DELTA = 416
  AW_AVATAR_WORLD_INSTANCE = 417
  AW_ATTRIB_SENDER_SESSION = 418
  AW_ENTITY_MODEL_NUM = 419
  AW_CITIZEN_COMMENT = 42
  AW_WORLD_V4_OBJECTS_RIGHT = 420
  AW_CITIZEN_LAST_ADDRESS = 421
  AW_HUD_ELEMENT_TYPE = 422
  AW_HUD_ELEMENT_ID = 423
  AW_HUD_ELEMENT_SESSION = 424
  AW_HUD_ELEMENT_ORIGIN = 425
  AW_HUD_ELEMENT_X = 426
  AW_HUD_ELEMENT_Y = 427
  AW_HUD_ELEMENT_Z = 428
  AW_HUD_ELEMENT_FLAGS = 429
  AW_CITIZEN_URL = 43
  AW_HUD_ELEMENT_TEXT = 430
  AW_HUD_ELEMENT_COLOR = 431
  AW_HUD_ELEMENT_OPACITY = 432
  AW_HUD_ELEMENT_SIZE_X = 433
  AW_HUD_ELEMENT_SIZE_Y = 434
  AW_HUD_ELEMENT_SIZE_Z = 435
  AW_HUD_ELEMENT_CLICK_X = 436
  AW_HUD_ELEMENT_CLICK_Y = 437
  AW_HUD_ELEMENT_CLICK_Z = 438
  AW_HUD_ELEMENT_TEXTURE_OFFSET_X = 439
  AW_WORLD_NAME = 44
  AW_HUD_ELEMENT_TEXTURE_OFFSET_Y = 440
  AW_CITIZEN_PRIVACY = 441
  AW_CITIZEN_TRIAL = 442
  AW_UNIVERSE_CAV_PATH2 = 443
  AW_WORLD_DISABLE_SHADOWS = 444
  AW_WORLD_ENABLE_CAMERA_COLLISION = 445
  AW_WORLD_SPECIAL_COMMANDS = 446
  AW_UNIVERSE_OBJECT_REFRESH = 447
  AW_UNIVERSE_OBJECT_PASSWORD = 448
  AW_CAV_SESSION = 449
  AW_WORLD_TITLE = 45
  AW_CITIZEN_CAV_ENABLED = 450
  AW_WORLD_CAV_OBJECT_PATH = 451
  AW_WORLD_CAV_OBJECT_PASSWORD = 452
  AW_WORLD_CAV_OBJECT_REFRESH = 453
  AW_OBJECT_CALLBACK_REFERENCE = 454
  AW_WORLD_TERRAIN_RIGHT = 455
  AW_UNIVERSE_ALLOW_TOURISTS_CAV = 456
  AW_UNIVERSE_ALLOW_BOTS_CAV = 457
  AW_WORLD_VOIP_CONFERENCE_GLOBAL = 458
  AW_WORLD_VOIP_MODERATE_GLOBAL = 459
  AW_WORLD_BACKDROP = 46
  AW_OBJECT_SESSION_TO = 460
  AW_WORLD_CAMERA_ZOOM = 461
  AW_WORLD_WAIT_LIMIT = 462
  AW_MAX_ATTRIBUTE = 463
  AW_WORLD_GROUND = 47
  AW_WORLD_OBJECT_PATH = 48
  AW_WORLD_OBJECT_REFRESH = 49
  AW_LOGIN_PRIVILEGE_NAME = 5
  AW_WORLD_BUILD_RIGHT = 50
  AW_WORLD_EMINENT_DOMAIN_RIGHT = 51
  AW_WORLD_ENTER_RIGHT = 52
  AW_WORLD_SPECIAL_OBJECTS_RIGHT = 53
  AW_WORLD_FOG_RED = 54
  AW_WORLD_FOG_GREEN = 55
  AW_WORLD_FOG_BLUE = 56
  AW_WORLD_CARETAKER_CAPABILITY = 57
  AW_WORLD_RESTRICTED_RADIUS = 58
  AW_WORLD_PUBLIC_SPEAKER_CAPABILITY = 59
  AW_LOGIN_APPLICATION = 6
  AW_WORLD_PUBLIC_SPEAKER_RIGHT = 60
  AW_WORLD_CREATION_TIMESTAMP = 61
  AW_WORLD_HOME_PAGE = 62
  AW_WORLD_BUILD_NUMBER = 63
  AW_WORLD_OBJECT_PASSWORD = 64
  AW_WORLD_DISABLE_CREATE_URL = 65
  AW_WORLD_RATING = 66
  AW_WORLD_WELCOME_MESSAGE = 67
  AW_WORLD_EJECT_RIGHT = 68
  AW_WORLD_EJECT_CAPABILITY = 69
  AW_LOGIN_EMAIL = 7
  AW_WORLD_CELL_LIMIT = 70
  AW_WORLD_BUILD_CAPABILITY = 71
  AW_WORLD_ALLOW_PASSTHRU = 72
  AW_WORLD_ALLOW_FLYING = 73
  AW_WORLD_ALLOW_TELEPORT = 74
  AW_WORLD_ALLOW_OBJECT_SELECT = 75
  AW_WORLD_BOTS_RIGHT = 76
  AW_WORLD_SPEAK_CAPABILITY = 77
  AW_WORLD_SPEAK_RIGHT = 78
  AW_WORLD_ALLOW_TOURIST_WHISPER = 79
  AW_UNIVERSE_BROWSER_MINIMUM = 8
  AW_WORLD_LIGHT_X = 80
  AW_WORLD_LIGHT_Y = 81
  AW_WORLD_LIGHT_Z = 82
  AW_WORLD_LIGHT_RED = 83
  AW_WORLD_LIGHT_GREEN = 84
  AW_WORLD_LIGHT_BLUE = 85
  AW_WORLD_AMBIENT_LIGHT_RED = 86
  AW_WORLD_AMBIENT_LIGHT_GREEN = 87
  AW_WORLD_AMBIENT_LIGHT_BLUE = 88
  AW_WORLD_ALLOW_AVATAR_COLLISION = 89
  AW_UNIVERSE_BROWSER_RELEASE = 9
  AW_WORLD_FOG_ENABLE = 90
  AW_WORLD_FOG_MINIMUM = 91
  AW_WORLD_FOG_MAXIMUM = 92
  AW_WORLD_FOG_TINTED = 93
  AW_WORLD_MAX_USERS = 94
  AW_WORLD_SIZE = 95
  AW_WORLD_OBJECT_COUNT = 96
  AW_WORLD_EXPIRATION = 97
  AW_WORLD_SPECIAL_COMMANDS_RIGHT = 98
  AW_WORLD_MAX_LIGHT_RADIUS = 99

  AW_ATTRIBUTE_ENUM = {
    :AW_LOGIN_NAME => 0,
    :AW_LOGIN_PASSWORD => 1,
    :AW_UNIVERSE_BROWSER_BETA => 10,
    :AW_WORLD_SKYBOX => 100,
    :AW_WORLD_MINIMUM_VISIBILITY => 101,
    :AW_WORLD_REPEATING_GROUND => 102,
    :AW_WORLD_KEYWORDS => 103,
    :AW_WORLD_ENABLE_TERRAIN => 104,
    :AW_WORLD_ALLOW_3_AXIS_ROTATION => 105,
    :AW_WORLD_TERRAIN_TIMESTAMP => 106,
    :AW_WORLD_ENTRY_POINT => 107,
    :AW_WORLD_SKY_NORTH_RED => 108,
    :AW_WORLD_SKY_NORTH_GREEN => 109,
    :AW_UNIVERSE_WORLD_MINIMUM => 11,
    :AW_WORLD_SKY_NORTH_BLUE => 110,
    :AW_WORLD_SKY_SOUTH_RED => 111,
    :AW_WORLD_SKY_SOUTH_GREEN => 112,
    :AW_WORLD_SKY_SOUTH_BLUE => 113,
    :AW_WORLD_SKY_EAST_RED => 114,
    :AW_WORLD_SKY_EAST_GREEN => 115,
    :AW_WORLD_SKY_EAST_BLUE => 116,
    :AW_WORLD_SKY_WEST_RED => 117,
    :AW_WORLD_SKY_WEST_GREEN => 118,
    :AW_WORLD_SKY_WEST_BLUE => 119,
    :AW_UNIVERSE_WORLD_START => 12,
    :AW_WORLD_SKY_TOP_RED => 120,
    :AW_WORLD_SKY_TOP_GREEN => 121,
    :AW_WORLD_SKY_TOP_BLUE => 122,
    :AW_WORLD_SKY_BOTTOM_RED => 123,
    :AW_WORLD_SKY_BOTTOM_GREEN => 124,
    :AW_WORLD_SKY_BOTTOM_BLUE => 125,
    :AW_WORLD_CLOUDS_LAYER1_TEXTURE => 126,
    :AW_WORLD_CLOUDS_LAYER1_MASK => 127,
    :AW_WORLD_CLOUDS_LAYER1_TILE => 128,
    :AW_WORLD_CLOUDS_LAYER1_SPEED_X => 129,
    :AW_UNIVERSE_REGISTRATION_REQUIRED => 13,
    :AW_WORLD_CLOUDS_LAYER1_SPEED_Z => 130,
    :AW_WORLD_CLOUDS_LAYER1_OPACITY => 131,
    :AW_WORLD_CLOUDS_LAYER2_TEXTURE => 132,
    :AW_WORLD_CLOUDS_LAYER2_MASK => 133,
    :AW_WORLD_CLOUDS_LAYER2_TILE => 134,
    :AW_WORLD_CLOUDS_LAYER2_SPEED_X => 135,
    :AW_WORLD_CLOUDS_LAYER2_SPEED_Z => 136,
    :AW_WORLD_CLOUDS_LAYER2_OPACITY => 137,
    :AW_WORLD_CLOUDS_LAYER3_TEXTURE => 138,
    :AW_WORLD_CLOUDS_LAYER3_MASK => 139,
    :AW_UNIVERSE_BUILD_NUMBER => 14,
    :AW_WORLD_CLOUDS_LAYER3_TILE => 140,
    :AW_WORLD_CLOUDS_LAYER3_SPEED_X => 141,
    :AW_WORLD_CLOUDS_LAYER3_SPEED_Z => 142,
    :AW_WORLD_CLOUDS_LAYER3_OPACITY => 143,
    :AW_WORLD_DISABLE_CHAT => 144,
    :AW_WORLD_ALLOW_CITIZEN_WHISPER => 145,
    :AW_WORLD_ALWAYS_SHOW_NAMES => 146,
    :AW_WORLD_DISABLE_AVATAR_LIST => 147,
    :AW_WORLD_AVATAR_REFRESH_RATE => 148,
    :AW_WORLD_WATER_TEXTURE => 149,
    :AW_UNIVERSE_MONTHLY_CHARGE => 15,
    :AW_WORLD_WATER_MASK => 150,
    :AW_WORLD_WATER_BOTTOM_TEXTURE => 151,
    :AW_WORLD_WATER_BOTTOM_MASK => 152,
    :AW_WORLD_WATER_OPACITY => 153,
    :AW_WORLD_WATER_RED => 154,
    :AW_WORLD_WATER_GREEN => 155,
    :AW_WORLD_WATER_BLUE => 156,
    :AW_WORLD_WATER_LEVEL => 157,
    :AW_WORLD_WATER_SURFACE_MOVE => 158,
    :AW_WORLD_WATER_WAVE_MOVE => 159,
    :AW_UNIVERSE_ANNUAL_CHARGE => 16,
    :AW_WORLD_WATER_SPEED => 160,
    :AW_WORLD_WATER_ENABLED => 161,
    :AW_WORLD_EMINENT_DOMAIN_CAPABILITY => 162,
    :AW_WORLD_LIGHT_TEXTURE => 163,
    :AW_WORLD_LIGHT_MASK => 164,
    :AW_WORLD_LIGHT_DRAW_SIZE => 165,
    :AW_WORLD_LIGHT_DRAW_FRONT => 166,
    :AW_WORLD_LIGHT_DRAW_BRIGHT => 167,
    :AW_WORLD_LIGHT_SOURCE_USE_COLOR => 168,
    :AW_WORLD_LIGHT_SOURCE_COLOR => 169,
    :AW_UNIVERSE_REGISTER_METHOD => 17,
    :AW_WORLD_TERRAIN_AMBIENT => 170,
    :AW_WORLD_TERRAIN_DIFFUSE => 171,
    :AW_WORLD_WATER_VISIBILITY => 172,
    :AW_WORLD_SOUND_FOOTSTEP => 173,
    :AW_WORLD_SOUND_WATER_ENTER => 174,
    :AW_WORLD_SOUND_WATER_EXIT => 175,
    :AW_WORLD_SOUND_AMBIENT => 176,
    :AW_WORLD_GRAVITY => 177,
    :AW_WORLD_BUOYANCY => 178,
    :AW_WORLD_FRICTION => 179,
    :AW_UNIVERSE_TIME => 18,
    :AW_WORLD_WATER_FRICTION => 180,
    :AW_WORLD_SLOPESLIDE_ENABLED => 181,
    :AW_WORLD_SLOPESLIDE_MIN_ANGLE => 182,
    :AW_WORLD_SLOPESLIDE_MAX_ANGLE => 183,
    :AW_WORLD_ALLOW_TOURIST_BUILD => 184,
    :AW_WORLD_ENABLE_REFERER => 185,
    :AW_WORLD_WATER_UNDER_TERRAIN => 186,
    :AW_WORLD_TERRAIN_OFFSET => 187,
    :AW_WORLD_VOIP_RIGHT => 188,
    :AW_WORLD_DISABLE_MULTIPLE_MEDIA => 189,
    :AW_UNIVERSE_CITIZEN_CHANGES_ALLOWED => 19,
    :AW_WORLD_BOTMENU_URL => 190,
    :AW_WORLD_ENABLE_BUMP_EVENT => 191,
    :AW_WORLD_ENABLE_SYNC_EVENTS => 192,
    :AW_WORLD_ENABLE_CAV => 193,
    :AW_WORLD_ENABLE_PAV => 194,
    :AW_WORLD_CHAT_DISABLE_URL_CLICKS => 195,
    :AW_WORLD_MOVER_EMPTY_RESET_TIMEOUT => 196,
    :AW_WORLD_MOVER_USED_RESET_TIMEOUT => 197,
    :AW_MY_X => 198,
    :AW_MY_Y => 199,
    :AW_LOGIN_OWNER => 2,
    :AW_UNIVERSE_BROWSER_RELEASE_22 => 20,
    :AW_MY_Z => 200,
    :AW_MY_YAW => 201,
    :AW_MY_PITCH => 202,
    :AW_MY_TYPE => 203,
    :AW_MY_GESTURE => 204,
    :AW_MY_STATE => 205,
    :AW_AVATAR_SESSION => 206,
    :AW_AVATAR_NAME => 207,
    :AW_AVATAR_X => 208,
    :AW_AVATAR_Y => 209,
    :AW_UNIVERSE_WELCOME_MESSAGE => 21,
    :AW_AVATAR_Z => 210,
    :AW_AVATAR_YAW => 211,
    :AW_AVATAR_PITCH => 212,
    :AW_AVATAR_TYPE => 213,
    :AW_AVATAR_GESTURE => 214,
    :AW_AVATAR_STATE => 215,
    :AW_AVATAR_ADDRESS => 216,
    :AW_AVATAR_VERSION => 217,
    :AW_AVATAR_CITIZEN => 218,
    :AW_AVATAR_PRIVILEGE => 219,
    :AW_UNIVERSE_WORLD_RELEASE => 22,
    :AW_AVATAR_LOCK => 220,
    :AW_AVATAR_FLAGS => 221,
    :AW_CHAT_SESSION => 222,
    :AW_CHAT_MESSAGE => 223,
    :AW_CELL_X => 224,
    :AW_CELL_Z => 225,
    :AW_CELL_SEQUENCE => 226,
    :AW_CELL_SIZE => 227,
    :AW_CELL_ITERATOR => 228,
    :AW_CELL_COMBINE => 229,
    :AW_UNIVERSE_WORLD_BETA => 23,
    :AW_OBJECT_ID => 230,
    :AW_OBJECT_NUMBER => 231,
    :AW_OBJECT_X => 232,
    :AW_OBJECT_Y => 233,
    :AW_OBJECT_Z => 234,
    :AW_OBJECT_YAW => 235,
    :AW_OBJECT_TILT => 236,
    :AW_OBJECT_ROLL => 237,
    :AW_OBJECT_MODEL => 238,
    :AW_OBJECT_DESCRIPTION => 239,
    :AW_UNIVERSE_ALLOW_TOURISTS => 24,
    :AW_OBJECT_ACTION => 240,
    :AW_OBJECT_OLD_NUMBER => 241,
    :AW_OBJECT_OLD_X => 242,
    :AW_OBJECT_OLD_Z => 243,
    :AW_OBJECT_OWNER => 244,
    :AW_OBJECT_SESSION => 245,
    :AW_OBJECT_BUILD_TIMESTAMP => 246,
    :AW_OBJECT_SYNC => 247,
    :AW_OBJECT_TYPE => 248,
    :AW_OBJECT_DATA => 249,
    :AW_UNIVERSE_SEARCH_URL => 25,
    :AW_QUERY_COMPLETE => 250,
    :AW_CHAT_TYPE => 251,
    :AW_LICENSE_NAME => 252,
    :AW_LICENSE_PASSWORD => 253,
    :AW_LICENSE_USERS => 254,
    :AW_LICENSE_RANGE => 255,
    :AW_LICENSE_EMAIL => 256,
    :AW_LICENSE_COMMENT => 257,
    :AW_LICENSE_CREATION_TIME => 258,
    :AW_LICENSE_EXPIRATION_TIME => 259,
    :AW_UNIVERSE_NOTEPAD_URL => 26,
    :AW_LICENSE_LAST_START => 260,
    :AW_LICENSE_LAST_ADDRESS => 261,
    :AW_LICENSE_HIDDEN => 262,
    :AW_LICENSE_ALLOW_TOURISTS => 263,
    :AW_LICENSE_VOIP => 264,
    :AW_LICENSE_PLUGINS => 265,
    :AW_WORLDLIST_NAME => 266,
    :AW_WORLDLIST_STATUS => 267,
    :AW_WORLDLIST_USERS => 268,
    :AW_WORLDLIST_RATING => 269,
    :AW_UNIVERSE_NAME => 27,
    :AW_WORLDLIST_MORE => 270,
    :AW_EJECT_SESSION => 271,
    :AW_EJECT_DURATION => 272,
    :AW_EJECTION_TYPE => 273,
    :AW_EJECTION_ADDRESS => 274,
    :AW_EJECTION_EXPIRATION_TIME => 275,
    :AW_EJECTION_CREATION_TIME => 276,
    :AW_EJECTION_COMMENT => 277,
    :AW_DISCONNECT_REASON => 278,
    :AW_FILE_RECIPIENT => 279,
    :AW_UNIVERSE_USER_LIST_ENABLED => 28,
    :AW_FILE_SENDER => 280,
    :AW_FILE_SENDER_NAME => 281,
    :AW_FILE_SESSION => 282,
    :AW_FILE_ADDRESS => 283,
    :AW_FILE_PORT => 284,
    :AW_CLICKED_SESSION => 285,
    :AW_CLICKED_NAME => 286,
    :AW_URL_NAME => 287,
    :AW_URL_POST => 288,
    :AW_URL_TARGET => 289,
    :AW_CITIZEN_NUMBER => 29,
    :AW_URL_TARGET_3D => 290,
    :AW_TELEPORT_WORLD => 291,
    :AW_TELEPORT_X => 292,
    :AW_TELEPORT_Y => 293,
    :AW_TELEPORT_Z => 294,
    :AW_TELEPORT_YAW => 295,
    :AW_TELEPORT_WARP => 296,
    :AW_SERVER_BUILD => 297,
    :AW_SERVER_NAME => 298,
    :AW_SERVER_PASSWORD => 299,
    :AW_LOGIN_PRIVILEGE_PASSWORD => 3,
    :AW_CITIZEN_NAME => 30,
    :AW_SERVER_REGISTRY => 300,
    :AW_SERVER_CARETAKERS => 301,
    :AW_SERVER_ID => 302,
    :AW_SERVER_INSTANCE => 303,
    :AW_SERVER_ENABLED => 304,
    :AW_SERVER_STATE => 305,
    :AW_SERVER_USERS => 306,
    :AW_SERVER_MAX_USERS => 307,
    :AW_SERVER_OBJECTS => 308,
    :AW_SERVER_SIZE => 309,
    :AW_CITIZEN_PASSWORD => 31,
    :AW_SERVER_EXPIRATION => 310,
    :AW_SERVER_START_RC => 311,
    :AW_SERVER_MORE => 312,
    :AW_SERVER_TERRAIN_NODES => 313,
    :AW_TERRAIN_X => 314,
    :AW_TERRAIN_Z => 315,
    :AW_TERRAIN_PAGE_X => 316,
    :AW_TERRAIN_PAGE_Z => 317,
    :AW_TERRAIN_NODE_X => 318,
    :AW_TERRAIN_NODE_Z => 319,
    :AW_CITIZEN_EMAIL => 32,
    :AW_TERRAIN_NODE_SIZE => 320,
    :AW_TERRAIN_NODE_TEXTURE_COUNT => 321,
    :AW_TERRAIN_NODE_HEIGHT_COUNT => 322,
    :AW_TERRAIN_NODE_TEXTURES => 323,
    :AW_TERRAIN_NODE_HEIGHTS => 324,
    :AW_TERRAIN_SEQUENCE => 325,
    :AW_TERRAIN_COMPLETE => 326,
    :AW_TERRAIN_VERSION_NEEDED => 327,
    :AW_ENTER_GLOBAL => 328,
    :AW_CONSOLE_RED => 329,
    :AW_CITIZEN_TIME_LEFT => 33,
    :AW_CONSOLE_GREEN => 330,
    :AW_CONSOLE_BLUE => 331,
    :AW_CONSOLE_BOLD => 332,
    :AW_CONSOLE_ITALICS => 333,
    :AW_CONSOLE_MESSAGE => 334,
    :AW_BOTGRAM_TO => 335,
    :AW_BOTGRAM_FROM => 336,
    :AW_BOTGRAM_FROM_NAME => 337,
    :AW_BOTGRAM_TYPE => 338,
    :AW_BOTGRAM_TEXT => 339,
    :AW_CITIZEN_PRIVILEGE_PASSWORD => 34,
    :AW_TOOLBAR_ID => 340,
    :AW_TOOLBAR_SESSION => 341,
    :AW_USERLIST_MORE => 342,
    :AW_USERLIST_NAME => 343,
    :AW_USERLIST_WORLD => 344,
    :AW_USERLIST_EMAIL => 345,
    :AW_USERLIST_CITIZEN => 346,
    :AW_USERLIST_PRIVILEGE => 347,
    :AW_USERLIST_STATE => 348,
    :AW_USERLIST_ADDRESS => 349,
    :AW_CITIZEN_IMMIGRATION_TIME => 35,
    :AW_USERLIST_ID => 350,
    :AW_SOUND_NAME => 351,
    :AW_CAMERA_LOCATION_TYPE => 352,
    :AW_CAMERA_LOCATION_OBJECT => 353,
    :AW_CAMERA_LOCATION_SESSION => 354,
    :AW_CAMERA_TARGET_TYPE => 355,
    :AW_CAMERA_TARGET_OBJECT => 356,
    :AW_CAMERA_TARGET_SESSION => 357,
    :AW_PLUGIN_STRING => 358,
    :AW_BOTMENU_TO_SESSION => 359,
    :AW_CITIZEN_EXPIRATION_TIME => 36,
    :AW_BOTMENU_FROM_NAME => 360,
    :AW_BOTMENU_FROM_SESSION => 361,
    :AW_BOTMENU_QUESTION => 362,
    :AW_BOTMENU_ANSWER => 363,
    :AW_CONTACT_NUMBER => 364,
    :AW_CONTACT_STATUS => 365,
    :AW_CONTACT_NAME => 366,
    :AW_CONTACT_WORLD => 367,
    :AW_CONTACT_MORE => 368,
    :AW_CONTACT_OPTIONS => 369,
    :AW_CITIZEN_BETA => 37,
    :AW_TELEGRAM_TO => 370,
    :AW_TELEGRAM_FROM => 371,
    :AW_TELEGRAM_TEXT => 372,
    :AW_TELEGRAM_SENT => 373,
    :AW_TELEGRAM_MORE => 374,
    :AW_JOIN_NAME => 375,
    :AW_JOIN_CITIZEN => 376,
    :AW_JOIN_WORLD => 377,
    :AW_JOIN_X => 378,
    :AW_JOIN_Y => 379,
    :AW_CITIZEN_LAST_LOGIN => 38,
    :AW_JOIN_Z => 380,
    :AW_JOIN_YAW => 381,
    :AW_REGISTER_CC_NAME => 382,
    :AW_REGISTER_CC_NUMBER => 383,
    :AW_REGISTER_CC_MONTH => 384,
    :AW_REGISTER_CC_YEAR => 385,
    :AW_REGISTER_ADDRESS => 386,
    :AW_REGISTER_CITY => 387,
    :AW_REGISTER_STATE => 388,
    :AW_REGISTER_ZIP => 389,
    :AW_CITIZEN_BOT_LIMIT => 39,
    :AW_REGISTER_PHONE_NUMBER => 390,
    :AW_REGISTER_BUSINESS_NAME => 391,
    :AW_REGISTER_VENDOR => 392,
    :AW_REGISTER_RESULT => 393,
    :AW_REGISTER_METHOD => 394,
    :AW_VOIP_DATA => 395,
    :AW_UNIVERSE_CAV_PATH => 396,
    :AW_CITIZEN_PAV_ENABLED => 397,
    :AW_CAV_CITIZEN => 398,
    :AW_CAV_DEFINITION => 399,
    :AW_LOGIN_PRIVILEGE_NUMBER => 4,
    :AW_CITIZEN_TOTAL_TIME => 40,
    :AW_ENTITY_TYPE => 400,
    :AW_ENTITY_ID => 401,
    :AW_ENTITY_STATE => 402,
    :AW_ENTITY_FLAGS => 403,
    :AW_ENTITY_X => 404,
    :AW_ENTITY_Y => 405,
    :AW_ENTITY_Z => 406,
    :AW_ENTITY_YAW => 407,
    :AW_ENTITY_PITCH => 408,
    :AW_ENTITY_ROLL => 409,
    :AW_CITIZEN_ENABLED => 41,
    :AW_ENTITY_OWNER_SESSION => 410,
    :AW_ENTITY_OWNER_CITIZEN => 411,
    :AW_AVATAR_DISTANCE => 412,
    :AW_AVATAR_ANGLE => 413,
    :AW_AVATAR_Y_DELTA => 414,
    :AW_AVATAR_YAW_DELTA => 415,
    :AW_AVATAR_PITCH_DELTA => 416,
    :AW_AVATAR_WORLD_INSTANCE => 417,
    :AW_ATTRIB_SENDER_SESSION => 418,
    :AW_ENTITY_MODEL_NUM => 419,
    :AW_CITIZEN_COMMENT => 42,
    :AW_WORLD_V4_OBJECTS_RIGHT => 420,
    :AW_CITIZEN_LAST_ADDRESS => 421,
    :AW_HUD_ELEMENT_TYPE => 422,
    :AW_HUD_ELEMENT_ID => 423,
    :AW_HUD_ELEMENT_SESSION => 424,
    :AW_HUD_ELEMENT_ORIGIN => 425,
    :AW_HUD_ELEMENT_X => 426,
    :AW_HUD_ELEMENT_Y => 427,
    :AW_HUD_ELEMENT_Z => 428,
    :AW_HUD_ELEMENT_FLAGS => 429,
    :AW_CITIZEN_URL => 43,
    :AW_HUD_ELEMENT_TEXT => 430,
    :AW_HUD_ELEMENT_COLOR => 431,
    :AW_HUD_ELEMENT_OPACITY => 432,
    :AW_HUD_ELEMENT_SIZE_X => 433,
    :AW_HUD_ELEMENT_SIZE_Y => 434,
    :AW_HUD_ELEMENT_SIZE_Z => 435,
    :AW_HUD_ELEMENT_CLICK_X => 436,
    :AW_HUD_ELEMENT_CLICK_Y => 437,
    :AW_HUD_ELEMENT_CLICK_Z => 438,
    :AW_HUD_ELEMENT_TEXTURE_OFFSET_X => 439,
    :AW_WORLD_NAME => 44,
    :AW_HUD_ELEMENT_TEXTURE_OFFSET_Y => 440,
    :AW_CITIZEN_PRIVACY => 441,
    :AW_CITIZEN_TRIAL => 442,
    :AW_UNIVERSE_CAV_PATH2 => 443,
    :AW_WORLD_DISABLE_SHADOWS => 444,
    :AW_WORLD_ENABLE_CAMERA_COLLISION => 445,
    :AW_WORLD_SPECIAL_COMMANDS => 446,
    :AW_UNIVERSE_OBJECT_REFRESH => 447,
    :AW_UNIVERSE_OBJECT_PASSWORD => 448,
    :AW_CAV_SESSION => 449,
    :AW_WORLD_TITLE => 45,
    :AW_CITIZEN_CAV_ENABLED => 450,
    :AW_WORLD_CAV_OBJECT_PATH => 451,
    :AW_WORLD_CAV_OBJECT_PASSWORD => 452,
    :AW_WORLD_CAV_OBJECT_REFRESH => 453,
    :AW_OBJECT_CALLBACK_REFERENCE => 454,
    :AW_WORLD_TERRAIN_RIGHT => 455,
    :AW_UNIVERSE_ALLOW_TOURISTS_CAV => 456,
    :AW_UNIVERSE_ALLOW_BOTS_CAV => 457,
    :AW_WORLD_VOIP_CONFERENCE_GLOBAL => 458,
    :AW_WORLD_VOIP_MODERATE_GLOBAL => 459,
    :AW_WORLD_BACKDROP => 46,
    :AW_OBJECT_SESSION_TO => 460,
    :AW_WORLD_CAMERA_ZOOM => 461,
    :AW_WORLD_WAIT_LIMIT => 462,
    :AW_MAX_ATTRIBUTE => 463,
    :AW_WORLD_GROUND => 47,
    :AW_WORLD_OBJECT_PATH => 48,
    :AW_WORLD_OBJECT_REFRESH => 49,
    :AW_LOGIN_PRIVILEGE_NAME => 5,
    :AW_WORLD_BUILD_RIGHT => 50,
    :AW_WORLD_EMINENT_DOMAIN_RIGHT => 51,
    :AW_WORLD_ENTER_RIGHT => 52,
    :AW_WORLD_SPECIAL_OBJECTS_RIGHT => 53,
    :AW_WORLD_FOG_RED => 54,
    :AW_WORLD_FOG_GREEN => 55,
    :AW_WORLD_FOG_BLUE => 56,
    :AW_WORLD_CARETAKER_CAPABILITY => 57,
    :AW_WORLD_RESTRICTED_RADIUS => 58,
    :AW_WORLD_PUBLIC_SPEAKER_CAPABILITY => 59,
    :AW_LOGIN_APPLICATION => 6,
    :AW_WORLD_PUBLIC_SPEAKER_RIGHT => 60,
    :AW_WORLD_CREATION_TIMESTAMP => 61,
    :AW_WORLD_HOME_PAGE => 62,
    :AW_WORLD_BUILD_NUMBER => 63,
    :AW_WORLD_OBJECT_PASSWORD => 64,
    :AW_WORLD_DISABLE_CREATE_URL => 65,
    :AW_WORLD_RATING => 66,
    :AW_WORLD_WELCOME_MESSAGE => 67,
    :AW_WORLD_EJECT_RIGHT => 68,
    :AW_WORLD_EJECT_CAPABILITY => 69,
    :AW_LOGIN_EMAIL => 7,
    :AW_WORLD_CELL_LIMIT => 70,
    :AW_WORLD_BUILD_CAPABILITY => 71,
    :AW_WORLD_ALLOW_PASSTHRU => 72,
    :AW_WORLD_ALLOW_FLYING => 73,
    :AW_WORLD_ALLOW_TELEPORT => 74,
    :AW_WORLD_ALLOW_OBJECT_SELECT => 75,
    :AW_WORLD_BOTS_RIGHT => 76,
    :AW_WORLD_SPEAK_CAPABILITY => 77,
    :AW_WORLD_SPEAK_RIGHT => 78,
    :AW_WORLD_ALLOW_TOURIST_WHISPER => 79,
    :AW_UNIVERSE_BROWSER_MINIMUM => 8,
    :AW_WORLD_LIGHT_X => 80,
    :AW_WORLD_LIGHT_Y => 81,
    :AW_WORLD_LIGHT_Z => 82,
    :AW_WORLD_LIGHT_RED => 83,
    :AW_WORLD_LIGHT_GREEN => 84,
    :AW_WORLD_LIGHT_BLUE => 85,
    :AW_WORLD_AMBIENT_LIGHT_RED => 86,
    :AW_WORLD_AMBIENT_LIGHT_GREEN => 87,
    :AW_WORLD_AMBIENT_LIGHT_BLUE => 88,
    :AW_WORLD_ALLOW_AVATAR_COLLISION => 89,
    :AW_UNIVERSE_BROWSER_RELEASE => 9,
    :AW_WORLD_FOG_ENABLE => 90,
    :AW_WORLD_FOG_MINIMUM => 91,
    :AW_WORLD_FOG_MAXIMUM => 92,
    :AW_WORLD_FOG_TINTED => 93,
    :AW_WORLD_MAX_USERS => 94,
    :AW_WORLD_SIZE => 95,
    :AW_WORLD_OBJECT_COUNT => 96,
    :AW_WORLD_EXPIRATION => 97,
    :AW_WORLD_SPECIAL_COMMANDS_RIGHT => 98,
    :AW_WORLD_MAX_LIGHT_RADIUS => 99,
  }

  AW_EVENT_AVATAR_ADD = 0
  AW_EVENT_AVATAR_CHANGE = 1
  AW_EVENT_UNIVERSE_DISCONNECT = 10
  AW_EVENT_WORLD_ATTRIBUTES = 11
  AW_EVENT_WORLD_INFO = 12
  AW_EVENT_WORLD_DISCONNECT = 13
  AW_EVENT_SEND_FILE = 14
  AW_EVENT_CONTACT_STATE = 15
  AW_EVENT_TELEGRAM = 16
  AW_EVENT_JOIN = 17
  AW_EVENT_OBJECT_CLICK = 18
  AW_EVENT_OBJECT_SELECT = 19
  AW_EVENT_AVATAR_DELETE = 2
  AW_EVENT_AVATAR_CLICK = 20
  AW_EVENT_URL = 21
  AW_EVENT_URL_CLICK = 22
  AW_EVENT_TELEPORT = 23
  AW_EVENT_ADMIN_WORLD_INFO = 24
  AW_EVENT_ADMIN_WORLD_DELETE = 25
  AW_EVENT_TERRAIN_BEGIN = 26
  AW_EVENT_TERRAIN_DATA = 27
  AW_EVENT_TERRAIN_END = 28
  AW_EVENT_CONSOLE_MESSAGE = 29
  AW_EVENT_CELL_BEGIN = 3
  AW_EVENT_TERRAIN_CHANGED = 30
  AW_EVENT_BOTGRAM = 31
  AW_EVENT_TOOLBAR_CLICK = 32
  AW_EVENT_USER_INFO = 33
  AW_EVENT_VOIP_DATA = 34
  AW_EVENT_NOISE = 35
  AW_EVENT_CAMERA = 36
  AW_EVENT_BOTMENU = 37
  AW_EVENT_OBJECT_BUMP = 38
  AW_EVENT_ENTITY_ADD = 39
  AW_EVENT_CELL_OBJECT = 4
  AW_EVENT_ENTITY_CHANGE = 40
  AW_EVENT_ENTITY_DELETE = 41
  AW_EVENT_ENTITY_RIDER_ADD = 42
  AW_EVENT_ENTITY_RIDER_DELETE = 43
  AW_EVENT_ENTITY_RIDER_CHANGE = 44
  AW_EVENT_AVATAR_RELOAD = 45
  AW_EVENT_ENTITY_LINKS = 46
  AW_EVENT_HUD_CLICK = 47
  AW_EVENT_HUD_CREATE = 48
  AW_EVENT_HUD_DESTROY = 49
  AW_EVENT_CELL_END = 5
  AW_EVENT_HUD_CLEAR = 50
  AW_EVENT_CAV_DEFINITION_CHANGE = 51
  AW_EVENT_WORLD_CAV_DEFINITION_CHANGE = 52
  AW_MAX_EVENT = 53
  AW_EVENT_CHAT = 6
  AW_EVENT_OBJECT_ADD = 7
  AW_EVENT_OBJECT_DELETE = 8
  AW_EVENT_UNIVERSE_ATTRIBUTES = 9

  AW_EVENT_ATTRIBUTE_ENUM = {
    :AW_EVENT_AVATAR_ADD => 0,
    :AW_EVENT_AVATAR_CHANGE => 1,
    :AW_EVENT_UNIVERSE_DISCONNECT => 10,
    :AW_EVENT_WORLD_ATTRIBUTES => 11,
    :AW_EVENT_WORLD_INFO => 12,
    :AW_EVENT_WORLD_DISCONNECT => 13,
    :AW_EVENT_SEND_FILE => 14,
    :AW_EVENT_CONTACT_STATE => 15,
    :AW_EVENT_TELEGRAM => 16,
    :AW_EVENT_JOIN => 17,
    :AW_EVENT_OBJECT_CLICK => 18,
    :AW_EVENT_OBJECT_SELECT => 19,
    :AW_EVENT_AVATAR_DELETE => 2,
    :AW_EVENT_AVATAR_CLICK => 20,
    :AW_EVENT_URL => 21,
    :AW_EVENT_URL_CLICK => 22,
    :AW_EVENT_TELEPORT => 23,
    :AW_EVENT_ADMIN_WORLD_INFO => 24,
    :AW_EVENT_ADMIN_WORLD_DELETE => 25,
    :AW_EVENT_TERRAIN_BEGIN => 26,
    :AW_EVENT_TERRAIN_DATA => 27,
    :AW_EVENT_TERRAIN_END => 28,
    :AW_EVENT_CONSOLE_MESSAGE => 29,
    :AW_EVENT_CELL_BEGIN => 3,
    :AW_EVENT_TERRAIN_CHANGED => 30,
    :AW_EVENT_BOTGRAM => 31,
    :AW_EVENT_TOOLBAR_CLICK => 32,
    :AW_EVENT_USER_INFO => 33,
    :AW_EVENT_VOIP_DATA => 34,
    :AW_EVENT_NOISE => 35,
    :AW_EVENT_CAMERA => 36,
    :AW_EVENT_BOTMENU => 37,
    :AW_EVENT_OBJECT_BUMP => 38,
    :AW_EVENT_ENTITY_ADD => 39,
    :AW_EVENT_CELL_OBJECT => 4,
    :AW_EVENT_ENTITY_CHANGE => 40,
    :AW_EVENT_ENTITY_DELETE => 41,
    :AW_EVENT_ENTITY_RIDER_ADD => 42,
    :AW_EVENT_ENTITY_RIDER_DELETE => 43,
    :AW_EVENT_ENTITY_RIDER_CHANGE => 44,
    :AW_EVENT_AVATAR_RELOAD => 45,
    :AW_EVENT_ENTITY_LINKS => 46,
    :AW_EVENT_HUD_CLICK => 47,
    :AW_EVENT_HUD_CREATE => 48,
    :AW_EVENT_HUD_DESTROY => 49,
    :AW_EVENT_CELL_END => 5,
    :AW_EVENT_HUD_CLEAR => 50,
    :AW_EVENT_CAV_DEFINITION_CHANGE => 51,
    :AW_EVENT_WORLD_CAV_DEFINITION_CHANGE => 52,
    :AW_MAX_EVENT => 53,
    :AW_EVENT_CHAT => 6,
    :AW_EVENT_OBJECT_ADD => 7,
    :AW_EVENT_OBJECT_DELETE => 8,
    :AW_EVENT_UNIVERSE_ATTRIBUTES => 9,
  }

  AW_CALLBACK_CREATE = 0
  AW_CALLBACK_LOGIN = 1
  AW_CALLBACK_SEND_FILE = 10
  AW_CALLBACK_JOIN = 11
  AW_CALLBACK_PASSWORD_SEND = 12
  AW_CALLBACK_IMMIGRATE = 13
  AW_CALLBACK_REGISTER = 14
  AW_CALLBACK_UNIVERSE_EJECTION = 15
  AW_CALLBACK_UNIVERSE_EJECTION_RESULT = 16
  AW_CALLBACK_ADDRESS = 17
  AW_CALLBACK_WORLD_EJECTION = 18
  AW_CALLBACK_WORLD_EJECTION_RESULT = 19
  AW_CALLBACK_ENTER = 2
  AW_CALLBACK_ADMIN_WORLD_LIST = 20
  AW_CALLBACK_ADMIN_WORLD_RESULT = 21
  AW_CALLBACK_DELETE_ALL_OBJECTS_RESULT = 22
  AW_CALLBACK_CELL_RESULT = 23
  AW_CALLBACK_RELOAD_REGISTRY = 24
  AW_CALLBACK_ATTRIBUTES_RESET_RESULT = 25
  AW_CALLBACK_ADMIN = 26
  AW_CALLBACK_CONTACT_ADD = 27
  AW_CALLBACK_TELEGRAM_RESULT = 28
  AW_CALLBACK_TERRAIN_SET_RESULT = 29
  AW_CALLBACK_OBJECT_RESULT = 3
  AW_CALLBACK_TERRAIN_NEXT_RESULT = 30
  AW_CALLBACK_TERRAIN_DELETE_ALL_RESULT = 31
  AW_CALLBACK_TERRAIN_LOAD_NODE_RESULT = 32
  AW_CALLBACK_BOTGRAM_RESULT = 33
  AW_CALLBACK_USER_LIST = 34
  AW_CALLBACK_BOTMENU_RESULT = 35
  AW_CALLBACK_CAV = 36
  AW_CALLBACK_CAV_RESULT = 37
  AW_CALLBACK_WORLD_INSTANCE = 38
  AW_CALLBACK_HUD_RESULT = 39
  AW_CALLBACK_LICENSE_ATTRIBUTES = 4
  AW_CALLBACK_AVATAR_LOCATION = 40
  AW_CALLBACK_OBJECT_QUERY = 41
  AW_CALLBACK_WORLD_CAV_RESULT = 42
  AW_CALLBACK_WORLD_CAV = 43
  AW_MAX_CALLBACK = 44
  AW_CALLBACK_LICENSE_RESULT = 5
  AW_CALLBACK_CITIZEN_ATTRIBUTES = 6
  AW_CALLBACK_CITIZEN_RESULT = 7
  AW_CALLBACK_QUERY = 8
  AW_CALLBACK_WORLD_LIST = 9

  AW_CALLBACK_ENUM = {
    :AW_CALLBACK_CREATE => 0,
    :AW_CALLBACK_LOGIN => 1,
    :AW_CALLBACK_SEND_FILE => 10,
    :AW_CALLBACK_JOIN => 11,
    :AW_CALLBACK_PASSWORD_SEND => 12,
    :AW_CALLBACK_IMMIGRATE => 13,
    :AW_CALLBACK_REGISTER => 14,
    :AW_CALLBACK_UNIVERSE_EJECTION => 15,
    :AW_CALLBACK_UNIVERSE_EJECTION_RESULT => 16,
    :AW_CALLBACK_ADDRESS => 17,
    :AW_CALLBACK_WORLD_EJECTION => 18,
    :AW_CALLBACK_WORLD_EJECTION_RESULT => 19,
    :AW_CALLBACK_ENTER => 2,
    :AW_CALLBACK_ADMIN_WORLD_LIST => 20,
    :AW_CALLBACK_ADMIN_WORLD_RESULT => 21,
    :AW_CALLBACK_DELETE_ALL_OBJECTS_RESULT => 22,
    :AW_CALLBACK_CELL_RESULT => 23,
    :AW_CALLBACK_RELOAD_REGISTRY => 24,
    :AW_CALLBACK_ATTRIBUTES_RESET_RESULT => 25,
    :AW_CALLBACK_ADMIN => 26,
    :AW_CALLBACK_CONTACT_ADD => 27,
    :AW_CALLBACK_TELEGRAM_RESULT => 28,
    :AW_CALLBACK_TERRAIN_SET_RESULT => 29,
    :AW_CALLBACK_OBJECT_RESULT => 3,
    :AW_CALLBACK_TERRAIN_NEXT_RESULT => 30,
    :AW_CALLBACK_TERRAIN_DELETE_ALL_RESULT => 31,
    :AW_CALLBACK_TERRAIN_LOAD_NODE_RESULT => 32,
    :AW_CALLBACK_BOTGRAM_RESULT => 33,
    :AW_CALLBACK_USER_LIST => 34,
    :AW_CALLBACK_BOTMENU_RESULT => 35,
    :AW_CALLBACK_CAV => 36,
    :AW_CALLBACK_CAV_RESULT => 37,
    :AW_CALLBACK_WORLD_INSTANCE => 38,
    :AW_CALLBACK_HUD_RESULT => 39,
    :AW_CALLBACK_LICENSE_ATTRIBUTES => 4,
    :AW_CALLBACK_AVATAR_LOCATION => 40,
    :AW_CALLBACK_OBJECT_QUERY => 41,
    :AW_CALLBACK_WORLD_CAV_RESULT => 42,
    :AW_CALLBACK_WORLD_CAV => 43,
    :AW_MAX_CALLBACK => 44,
    :AW_CALLBACK_LICENSE_RESULT => 5,
    :AW_CALLBACK_CITIZEN_ATTRIBUTES => 6,
    :AW_CALLBACK_CITIZEN_RESULT => 7,
    :AW_CALLBACK_QUERY => 8,
    :AW_CALLBACK_WORLD_LIST => 9,
  }

  AW_CHAT_SAID = 0
  AW_CHAT_BROADCAST = 1
  AW_CHAT_WHISPER = 2

  AW_CHAT_TYPES_ENUM = {
    :AW_CHAT_SAID => 0,
    :AW_CHAT_BROADCAST => 1,
    :AW_CHAT_WHISPER => 2,
  }

  AW_CONTACT_OFFLINE = 0
  AW_CONTACT_ONLINE = 1
  AW_CONTACT_NOT_A_CITIZEN = 2
  AW_CONTACT_AFK = 3
  AW_CONTACT_UNKNOWN = 4
  AW_CONTACT_DELETE = 5

  AW_CONTACT_STATES_ENUM = {
    :AW_CONTACT_OFFLINE => 0,
    :AW_CONTACT_ONLINE => 1,
    :AW_CONTACT_NOT_A_CITIZEN => 2,
    :AW_CONTACT_AFK => 3,
    :AW_CONTACT_UNKNOWN => 4,
    :AW_CONTACT_DELETE => 5,
  }

  AW_WORLDSTATUS_UNKNOWN = 0
  AW_WORLDSTATUS_PUBLIC = 1
  AW_WORLDSTATUS_PRIVATE = 2
  AW_WORLDSTATUS_STOPPED = 3

  AW_WORLD_STATES_ENUM = {
    :AW_WORLDSTATUS_UNKNOWN => 0,
    :AW_WORLDSTATUS_PUBLIC => 1,
    :AW_WORLDSTATUS_PRIVATE => 2,
    :AW_WORLDSTATUS_STOPPED => 3,
  }

  AW_SERVER_STOPPED = 0
  AW_SERVER_STARTING = 1
  AW_SERVER_START_WAIT = 2
  AW_SERVER_RUNNING = 3

  AW_SERVER_STATES_ENUM = {
    :AW_SERVER_STOPPED => 0,
    :AW_SERVER_STARTING => 1,
    :AW_SERVER_START_WAIT => 2,
    :AW_SERVER_RUNNING => 3,
  }

  AW_CONNECTION_DIRECT = 0
  AW_CONNECTION_FIREWALL_NO_PROXY = 1
  AW_CONNECTION_PROXY_AUTO = 2
  AW_CONNECTION_PROXY_NO_AUTH = 3
  AW_CONNECTION_PROXY_BASIC = 4
  AW_CONNECTION_PROXY_AUTH_NTLM = 5
  AW_CONNECTION_MAX = 6

  AW_CONNECTION_TYPES_ENUM = {
    :AW_CONNECTION_DIRECT => 0,
    :AW_CONNECTION_FIREWALL_NO_PROXY => 1,
    :AW_CONNECTION_PROXY_AUTO => 2,
    :AW_CONNECTION_PROXY_NO_AUTH => 3,
    :AW_CONNECTION_PROXY_BASIC => 4,
    :AW_CONNECTION_PROXY_AUTH_NTLM => 5,
    :AW_CONNECTION_MAX => 6,
  }

  AW_CONNECTION_STATE_NOT_CONNECTED = 0
  AW_CONNECTION_STATE_CONNECTING_TO_PROXY = 1
  AW_CONNECTION_STATE_NEGOTIATING_WITH_PROXY = 2
  AW_CONNECTION_STATE_CONNECTING_TO_TUNNEL = 3
  AW_CONNECTION_STATE_CONNECTING_TO_UNIVERSE = 4
  AW_CONNECTION_STATE_CONNECTED = 5
  AW_CONNECTION_STATE_PASSWORD_REQUIRED = 6

  AW_CONNECTION_STATES_ENUM = {
    :AW_CONNECTION_STATE_NOT_CONNECTED => 0,
    :AW_CONNECTION_STATE_CONNECTING_TO_PROXY => 1,
    :AW_CONNECTION_STATE_NEGOTIATING_WITH_PROXY => 2,
    :AW_CONNECTION_STATE_CONNECTING_TO_TUNNEL => 3,
    :AW_CONNECTION_STATE_CONNECTING_TO_UNIVERSE => 4,
    :AW_CONNECTION_STATE_CONNECTED => 5,
    :AW_CONNECTION_STATE_PASSWORD_REQUIRED => 6,
  }

  AW_EJECT_BY_ADDRESS = 0
  AW_EJECT_BY_COMPUTER = 1
  AW_EJECT_BY_CITIZEN = 2

  AW_EJECTION_TYPES_ENUM = {
    :AW_EJECT_BY_ADDRESS => 0,
    :AW_EJECT_BY_COMPUTER => 1,
    :AW_EJECT_BY_CITIZEN => 2,
  }

  AW_AVATAR_STATE_WALKING = 0
  AW_AVATAR_STATE_RUNNING = 1
  AW_AVATAR_STATE_SLIDING3 = 10
  AW_AVATAR_STATE_CLIMBING = 11
  AW_AVATAR_STATE_FLYING = 2
  AW_AVATAR_STATE_SWIMMING = 3
  AW_AVATAR_STATE_FALLING = 4
  AW_AVATAR_STATE_JUMPING = 5
  AW_AVATAR_STATE_WARPING = 6
  AW_AVATAR_STATE_RIDING = 7
  AW_AVATAR_STATE_SLIDING1 = 8
  AW_AVATAR_STATE_SLIDING2 = 9

  AW_AVATAR_STATES_ENUM = {
    :AW_AVATAR_STATE_WALKING => 0,
    :AW_AVATAR_STATE_RUNNING => 1,
    :AW_AVATAR_STATE_SLIDING3 => 10,
    :AW_AVATAR_STATE_CLIMBING => 11,
    :AW_AVATAR_STATE_FLYING => 2,
    :AW_AVATAR_STATE_SWIMMING => 3,
    :AW_AVATAR_STATE_FALLING => 4,
    :AW_AVATAR_STATE_JUMPING => 5,
    :AW_AVATAR_STATE_WARPING => 6,
    :AW_AVATAR_STATE_RIDING => 7,
    :AW_AVATAR_STATE_SLIDING1 => 8,
    :AW_AVATAR_STATE_SLIDING2 => 9,
  }

  AW_ZONE_TYPE_CUBE = 0
  AW_ZONE_TYPE_CYLINDER = 1
  AW_ZONE_TYPE_SPHERE = 2

  AW_ZONE_TYPES_ENUM = {
    :AW_ZONE_TYPE_CUBE => 0,
    :AW_ZONE_TYPE_CYLINDER => 1,
    :AW_ZONE_TYPE_SPHERE => 2,
  }

  AW_PARTICLE_TYPE_SPRITE = 0
  AW_PARTICLE_TYPE_FACER = 1
  AW_PARTICLE_TYPE_FLAT = 2
  AW_PARTICLE_TYPE_OBJECT = 3

  AW_PARTICLE_TYPES_ENUM = {
    :AW_PARTICLE_TYPE_SPRITE => 0,
    :AW_PARTICLE_TYPE_FACER => 1,
    :AW_PARTICLE_TYPE_FLAT => 2,
    :AW_PARTICLE_TYPE_OBJECT => 3,
  }

  AW_PARTICLE_DRAW_NORMAL = 0
  AW_PARTICLE_DRAW_BRIGHT = 1
  AW_PARTICLE_DRAW_GLOW = 2

  AW_PARTICLE_DRAW_STYLES_ENUM = {
    :AW_PARTICLE_DRAW_NORMAL => 0,
    :AW_PARTICLE_DRAW_BRIGHT => 1,
    :AW_PARTICLE_DRAW_GLOW => 2,
  }

  AW_CAMERA_TRACK_DEFAULT = 0
  AW_CAMERA_TRACK_AVATAR = 1
  AW_CAMERA_TRACK_OBJECT = 2
  AW_CAMERA_TRACK_AHEAD = 3

  AW_CAMERA_TYPES_ENUM = {
    :AW_CAMERA_TRACK_DEFAULT => 0,
    :AW_CAMERA_TRACK_AVATAR => 1,
    :AW_CAMERA_TRACK_OBJECT => 2,
    :AW_CAMERA_TRACK_AHEAD => 3,
  }

  AW_REGISTER_MONTHLY = 0
  AW_REGISTER_ANNUAL = 1
  AW_REGISTER_USER = 2

  AW_REGISTER_METHODS_ENUM = {
    :AW_REGISTER_MONTHLY => 0,
    :AW_REGISTER_ANNUAL => 1,
    :AW_REGISTER_USER => 2,
  }

  AW_AVATAR_SET_NONE = 0x00
  AW_AVATAR_SET_POSITION = 0x01
  AW_AVATAR_SET_TYPE = 0x02
  AW_AVATAR_SET_GESTURE = 0x04
  AW_AVATAR_SET_STATE = 0x08

  AW_AVATAR_SET_FLAGS_ENUM = {
    :AW_AVATAR_SET_NONE => 0x00,
    :AW_AVATAR_SET_POSITION => 0x01,
    :AW_AVATAR_SET_TYPE => 0x02,
    :AW_AVATAR_SET_GESTURE => 0x04,
    :AW_AVATAR_SET_STATE => 0x08,
  }

  AW_ENTITY_AVATAR = 0
  AW_ENTITY_MOVER = 1

  AW_ENTITY_TYPES_ENUM = {
    :AW_ENTITY_AVATAR => 0,
    :AW_ENTITY_MOVER => 1,
  }

  AW_MOVER_STATE_IDLE = 0
  AW_MOVER_STATE_START = 1
  AW_MOVER_STATE_MOVE = 2
  AW_MOVER_STATE_PAUSE = 3
  AW_MOVER_STATE_CONTINUE = 4
  AW_MOVER_STATE_STOP = 5
  AW_MOVER_STATE_RESET = 6

  AW_MOVER_STATE_TYPES_ENUM = {
    :AW_MOVER_STATE_IDLE => 0,
    :AW_MOVER_STATE_START => 1,
    :AW_MOVER_STATE_MOVE => 2,
    :AW_MOVER_STATE_PAUSE => 3,
    :AW_MOVER_STATE_CONTINUE => 4,
    :AW_MOVER_STATE_STOP => 5,
    :AW_MOVER_STATE_RESET => 6,
  }

  AW_MOVER_FLAG_LOOP = 0x00000001
  AW_MOVER_FLAG_USE_OBJTAG = 0x00000002
  AW_MOVER_FLAG_BUMP_ADD = 0x00000004
  AW_MOVER_FLAG_CLICK_START = 0x00000008
  AW_MOVER_FLAG_CLICK_PAUSE = 0x00000010
  AW_MOVER_FLAG_LOCK_POSITION = 0x00000020
  AW_MOVER_FLAG_LOCK_YAW = 0x00000040
  AW_MOVER_FLAG_LOCK_PITCH = 0x00000080
  AW_MOVER_FLAG_SINGLE_RIDER = 0x00000100
  AW_MOVER_FLAG_NO_AUTO_YAW = 0x00000200
  AW_MOVER_FLAG_EMPTY_RESET = 0x00000400
  AW_MOVER_FLAG_DISABLE_FLYING = 0x00000800
  AW_MOVER_FLAG_KEEP_ON_WATER = 0x00001000
  AW_MOVER_FLAG_DISABLE_UPWARDS = 0x00002000
  AW_MOVER_FLAG_INVISIBLE_AV = 0x00004000
  AW_MOVER_FLAG_EXIT_EJECT_UP = 0x00008000
  AW_MOVER_FLAG_EXIT_NON_SOLID = 0x00010000
  AW_MOVER_FLAG_AV_APPLY_TILT_X = 0x00020000
  AW_MOVER_FLAG_AV_APPLY_TILT_Z = 0x00040000
  AW_MOVER_FLAG_OBJECT_LINK = 0x00080000
  AW_MOVER_FLAG_DISABLE_MOVE = 0x00100000
  AW_MOVER_FLAG_TILT_BY_TERRAIN = 0x00200000
  AW_MOVER_FLAG_DISABLE_EXPL_SEQS = 0x00400000
  AW_MOVER_FLAG_DISABLE_TURN_ON_PLACE = 0x00800000
  AW_MOVER_FLAG_DISABLE_TELEPORTS = 0x01000000
  AW_MOVER_FLAG_DETACH_ON_TELEPORT = 0x02000000

  AW_MOVER_FLAGS_ENUM = {
    :AW_MOVER_FLAG_LOOP => 0x00000001,
    :AW_MOVER_FLAG_USE_OBJTAG => 0x00000002,
    :AW_MOVER_FLAG_BUMP_ADD => 0x00000004,
    :AW_MOVER_FLAG_CLICK_START => 0x00000008,
    :AW_MOVER_FLAG_CLICK_PAUSE => 0x00000010,
    :AW_MOVER_FLAG_LOCK_POSITION => 0x00000020,
    :AW_MOVER_FLAG_LOCK_YAW => 0x00000040,
    :AW_MOVER_FLAG_LOCK_PITCH => 0x00000080,
    :AW_MOVER_FLAG_SINGLE_RIDER => 0x00000100,
    :AW_MOVER_FLAG_NO_AUTO_YAW => 0x00000200,
    :AW_MOVER_FLAG_EMPTY_RESET => 0x00000400,
    :AW_MOVER_FLAG_DISABLE_FLYING => 0x00000800,
    :AW_MOVER_FLAG_KEEP_ON_WATER => 0x00001000,
    :AW_MOVER_FLAG_DISABLE_UPWARDS => 0x00002000,
    :AW_MOVER_FLAG_INVISIBLE_AV => 0x00004000,
    :AW_MOVER_FLAG_EXIT_EJECT_UP => 0x00008000,
    :AW_MOVER_FLAG_EXIT_NON_SOLID => 0x00010000,
    :AW_MOVER_FLAG_AV_APPLY_TILT_X => 0x00020000,
    :AW_MOVER_FLAG_AV_APPLY_TILT_Z => 0x00040000,
    :AW_MOVER_FLAG_OBJECT_LINK => 0x00080000,
    :AW_MOVER_FLAG_DISABLE_MOVE => 0x00100000,
    :AW_MOVER_FLAG_TILT_BY_TERRAIN => 0x00200000,
    :AW_MOVER_FLAG_DISABLE_EXPL_SEQS => 0x00400000,
    :AW_MOVER_FLAG_DISABLE_TURN_ON_PLACE => 0x00800000,
    :AW_MOVER_FLAG_DISABLE_TELEPORTS => 0x01000000,
    :AW_MOVER_FLAG_DETACH_ON_TELEPORT => 0x02000000,
  }

  AW_MOVER_TYPE_PASSIVE = 0
  AW_MOVER_TYPE_ACTIVE = 1
  AW_MOVER_TYPE_ITEM = 2

  AW_MOVER_TYPES_ENUM = {
    :AW_MOVER_TYPE_PASSIVE => 0,
    :AW_MOVER_TYPE_ACTIVE => 1,
    :AW_MOVER_TYPE_ITEM => 2,
  }

  AW_ZONE_FLAG_WATER = 0x01
  AW_ZONE_FLAG_BLOCK_PARTICLES = 0x02
  AW_ZONE_FLAG_BLOCK_LIGHTS = 0x04
  AW_ZONE_FLAG_BLOCK_WORLD_LIGHT = 0x08
  AW_ZONE_FLAG_BLOCK_CHAT = 0x10
  AW_ZONE_FLAG_VISIBLE = 0x20
  AW_ZONE_FLAG_BLOCK_JOIN = 0x40
  AW_ZONE_FLAG_VOIP = 0x80

  AW_ZONE_FLAGS_ENUM = {
    :AW_ZONE_FLAG_WATER => 0x01,
    :AW_ZONE_FLAG_BLOCK_PARTICLES => 0x02,
    :AW_ZONE_FLAG_BLOCK_LIGHTS => 0x04,
    :AW_ZONE_FLAG_BLOCK_WORLD_LIGHT => 0x08,
    :AW_ZONE_FLAG_BLOCK_CHAT => 0x10,
    :AW_ZONE_FLAG_VISIBLE => 0x20,
    :AW_ZONE_FLAG_BLOCK_JOIN => 0x40,
    :AW_ZONE_FLAG_VOIP => 0x80,
  }

  AW_PARTICLE_FLAG_INTERPOLATE = 0x01
  AW_PARTICLE_FLAG_GRAVITY = 0x02
  AW_PARTICLE_FLAG_COLLIDE_ZONES = 0x04
  AW_PARTICLE_FLAG_ZONE_EXCLUSIVE = 0x08
  AW_PARTICLE_FLAG_CAMERA_EMIT = 0x10
  AW_PARTICLE_FLAG_MOVER_LINK = 0x20
  AW_PARTICLE_FLAG_DRAW_IN_FRONT = 0x40

  AW_PARTICLE_FLAGS_ENUM = {
    :AW_PARTICLE_FLAG_INTERPOLATE => 0x01,
    :AW_PARTICLE_FLAG_GRAVITY => 0x02,
    :AW_PARTICLE_FLAG_COLLIDE_ZONES => 0x04,
    :AW_PARTICLE_FLAG_ZONE_EXCLUSIVE => 0x08,
    :AW_PARTICLE_FLAG_CAMERA_EMIT => 0x10,
    :AW_PARTICLE_FLAG_MOVER_LINK => 0x20,
    :AW_PARTICLE_FLAG_DRAW_IN_FRONT => 0x40,
  }

  AW_CAMERA_FLAG_TRACK_USER = 0x01

  AW_CAMERA_FLAGS_ENUM = {
    :AW_CAMERA_FLAG_TRACK_USER => 0x01,
  }

  AW_OBJECT_TYPE_V3 = 0
  AW_OBJECT_TYPE_UNKNOWN = 1
  AW_OBJECT_TYPE_ZONE = 2
  AW_OBJECT_TYPE_PARTICLES = 3
  AW_OBJECT_TYPE_MOVER = 4
  AW_OBJECT_TYPE_CAMERA = 5
  AW_MAX_OBJECT_TYPES = 6

  AW_OBJECT_TYPES_ENUM = {
    :AW_OBJECT_TYPE_V3 => 0,
    :AW_OBJECT_TYPE_UNKNOWN => 1,
    :AW_OBJECT_TYPE_ZONE => 2,
    :AW_OBJECT_TYPE_PARTICLES => 3,
    :AW_OBJECT_TYPE_MOVER => 4,
    :AW_OBJECT_TYPE_CAMERA => 5,
    :AW_MAX_OBJECT_TYPES => 6,
  }

  AW_HUD_ORIGIN_TOP_LEFT = 0
  AW_HUD_ORIGIN_TOP = 1
  AW_HUD_ORIGIN_TOP_RIGHT = 2
  AW_HUD_ORIGIN_LEFT = 3
  AW_HUD_ORIGIN_CENTER = 4
  AW_HUD_ORIGIN_RIGHT = 5
  AW_HUD_ORIGIN_BOTTOM_LEFT = 6
  AW_HUD_ORIGIN_BOTTOM = 7
  AW_HUD_ORIGIN_BOTTOM_RIGHT = 8

  AW_HUD_ORIGIN_TYPES_ENUM = {
    :AW_HUD_ORIGIN_TOP_LEFT => 0,
    :AW_HUD_ORIGIN_TOP => 1,
    :AW_HUD_ORIGIN_TOP_RIGHT => 2,
    :AW_HUD_ORIGIN_LEFT => 3,
    :AW_HUD_ORIGIN_CENTER => 4,
    :AW_HUD_ORIGIN_RIGHT => 5,
    :AW_HUD_ORIGIN_BOTTOM_LEFT => 6,
    :AW_HUD_ORIGIN_BOTTOM => 7,
    :AW_HUD_ORIGIN_BOTTOM_RIGHT => 8,
  }

  AW_HUD_TYPE_TEXT = 0
  AW_HUD_TYPE_IMAGE = 1
  AW_HUD_TYPE_MODEL = 2

  AW_HUD_TYPES_ENUM = {
    :AW_HUD_TYPE_TEXT => 0,
    :AW_HUD_TYPE_IMAGE => 1,
    :AW_HUD_TYPE_MODEL => 2,
  }

  AW_HUD_ELEMENT_FLAG_CLICKS = 0x0001
  AW_HUD_ELEMENT_FLAG_STRETCH = 0x0002
  AW_HUD_ELEMENT_FLAG_ADDITIVE = 0x0004
  AW_HUD_ELEMENT_FLAG_SIZE_PERCENT = 0x0008
  AW_HUD_ELEMENT_FLAG_TRANSITION = 0x0010
  AW_HUD_ELEMENT_FLAG_TEMPORARY = 0x0020
  AW_HUD_ELEMENT_FLAG_UNIVERSE_PATH = 0x0040
  AW_HUD_ELEMENT_FLAG_CLAMP = 0x0080
  AW_HUD_ELEMENT_FLAG_HIGHLIGHT = 0x0100

  AW_HUD_ELEMENT_FLAGS_ENUM_ENUM = {
    :AW_HUD_ELEMENT_FLAG_CLICKS => 0x0001,
    :AW_HUD_ELEMENT_FLAG_STRETCH => 0x0002,
    :AW_HUD_ELEMENT_FLAG_ADDITIVE => 0x0004,
    :AW_HUD_ELEMENT_FLAG_SIZE_PERCENT => 0x0008,
    :AW_HUD_ELEMENT_FLAG_TRANSITION => 0x0010,
    :AW_HUD_ELEMENT_FLAG_TEMPORARY => 0x0020,
    :AW_HUD_ELEMENT_FLAG_UNIVERSE_PATH => 0x0040,
    :AW_HUD_ELEMENT_FLAG_CLAMP => 0x0080,
    :AW_HUD_ELEMENT_FLAG_HIGHLIGHT => 0x0100,
  }

  AW_PRIVACY_BLOCK_TELEGRAMS = 0x0001

  AW_PRIVACY_TYPES_ENUM = {
    :AW_PRIVACY_BLOCK_TELEGRAMS => 0x0001,
  }

  AW_ENABLE_CAV_CITIZEN = 0x01
  AW_ENABLE_CAV_BOT = 0x02
  AW_ENABLE_CAV_TOURIST = 0x04
  AW_ENABLE_CAV_WORLD_CITIZEN = 0x10
  AW_ENABLE_CAV_WORLD_BOT = 0x20
  AW_ENABLE_CAV_WORLD_TOURIST = 0x40

  AW_ENABLE_CAV_TYPES_ENUM = {
    :AW_ENABLE_CAV_CITIZEN => 0x01,
    :AW_ENABLE_CAV_BOT => 0x02,
    :AW_ENABLE_CAV_TOURIST => 0x04,
    :AW_ENABLE_CAV_WORLD_CITIZEN => 0x10,
    :AW_ENABLE_CAV_WORLD_BOT => 0x20,
    :AW_ENABLE_CAV_WORLD_TOURIST => 0x40,
  }

  class AwTypeVector < FFI::Struct
    layout(
           :x, :float,
           :y, :float,
           :z, :float
    )
  end
  class AwTypeVectorRange < FFI::Struct
    layout(
           :min, AwTypeVector,
           :max, AwTypeVector
    )
  end
  class AwObjectDataZone < FFI::Struct
    layout(
           :size, AwTypeVector,
           :version, :uchar,
           :shape, :uchar,
           :priority, :char,
           :gravity, :float,
           :friction, :float,
           :flags, :ushort,
           :color, :ulong,
           :fog_min, :ushort,
           :fog_max, :ushort,
           :footstep_len, :ushort,
           :ambient_len, :ushort,
           :camera_len, :uchar,
           :target_cur_len, :uchar,
           :voip_rights_len, :uchar,
           :name_len, :uchar,
           :reserved, [:char, 9],
           :str_data, [:char, 1]
    )
  end
  class AwObjectDataParticles < FFI::Struct
    layout(
           :volume, AwTypeVectorRange,
           :version, :uchar,
           :speed, AwTypeVectorRange,
           :accel, AwTypeVectorRange,
           :angle, AwTypeVectorRange,
           :spin, AwTypeVectorRange,
           :size, AwTypeVectorRange,
           :release_min, :ulong,
           :release_max, :ulong,
           :release_size, :ushort,
           :lifespan, :ulong,
           :emitter_lifespan, :ulong,
           :fade_in, :ulong,
           :fade_out, :ulong,
           :color_start, :ulong,
           :color_end, :ulong,
           :opacity, :float,
           :render_style, :uchar,
           :flags, :ushort,
           :style, :uchar,
           :asset_list_len, :ushort,
           :name_len, :uchar,
           :reserved, [:char, 12],
           :str_data, [:char, 1]
    )
  end
  class AwObjectDataCamera < FFI::Struct
    layout(
           :version, :uchar,
           :flags, :ushort,
           :zoom, :float,
           :name_len, :uchar,
           :reserved, [:char, 12],
           :str_data, [:char, 1]
    )
  end
  class AwObjectDataMover < FFI::Struct
    layout(
           :version, :uchar,
           :type, :uchar,
           :flags, :uint,
           :locked_pos_x, :short,
           :locked_pos_y, :short,
           :locked_pos_z, :short,
           :locked_yaw, :short,
           :locked_pitch, :short,
           :glide_factor, :char,
           :speed_factor, :uchar,
           :friction_factor, :uchar,
           :accel_tilt_x, :char,
           :accel_tilt_z, :char,
           :turn_factor, :uchar,
           :avatar_tag, :uchar,
           :reserved1, [:char, 9],
           :name_len, :uchar,
           :seq_len, :uchar,
           :script_len, :uchar,
           :sound_len, :uchar,
           :waypoints_len, :ushort,
           :bump_name_len, :uchar,
           :reserved2, [:char, 2],
           :str_data, [:char, 1]
    )
  end
  class AwWaypoint < FFI::Struct
    layout(
           :x, :short,
           :y, :short,
           :z, :short,
           :yaw, :short,
           :pitch, :short,
           :roll, :short,
           :speed, :ushort,
           :pause, :uchar,
           :flag, :ushort
    )
  end
  attach_function :aw_init, [ :int ], :int
  attach_function :aw_init_bind, [ :int, :ulong ], :int
  attach_function :aw_term, [  ], :void
  attach_function :aw_create, [ :string, :int, :pointer ], :int
  attach_function :aw_create_resolved, [ :ulong, :int, :pointer ], :int
  attach_function :aw_destroy, [  ], :int
  attach_function :aw_instance, [  ], :pointer
  attach_function :aw_instance_set, [ :pointer ], :int
  attach_function :aw_login, [  ], :int
  attach_function :aw_wait, [ :int ], :int
  attach_function :aw_int, [ :int ], :int
  attach_function :aw_int_set, [ :int, :int ], :int
  attach_function :aw_string, [ :int ], :string
  attach_function :aw_string_set, [ :int, :string ], :int
  attach_function :aw_bool, [ :int ], :int
  attach_function :aw_bool_set, [ :int, :int ], :int
  attach_function :aw_float, [ :int ], :float
  attach_function :aw_float_set, [ :int, :float ], :int
  attach_function :aw_data, [ :int, :pointer ], :string
  attach_function :aw_data_set, [ :int, :string, :uint ], :int
  attach_function :aw_callback, [ :int ], :pointer
  # attach_function :aw_callback_set, [ :int, callback([ :int ], :void) ], :int
  # attach_function :aw_instance_callback_set, [ :int, callback([ :int ], :void) ], :int
  attach_function :aw_event, [ :int ], :pointer
  # attach_function :aw_event_set, [ :int, callback([  ], :void) ], :int
  # attach_function :aw_instance_event_set, [ :int, callback([  ], :void) ], :int
  attach_function :aw_enter, [ :string ], :int
  attach_function :aw_exit, [  ], :int
  attach_function :aw_say, [ :string ], :int
  attach_function :aw_whisper, [ :int, :string ], :int
  attach_function :aw_state_change, [  ], :int
  attach_function :aw_citizen_attributes_by_name, [ :string ], :int
  attach_function :aw_citizen_attributes_by_number, [ :int ], :int
  attach_function :aw_citizen_add, [  ], :int
  attach_function :aw_citizen_change, [  ], :int
  attach_function :aw_citizen_delete, [ :int ], :int
  attach_function :aw_citizen_next, [  ], :int
  attach_function :aw_citizen_previous, [  ], :int
  attach_function :aw_cav_request, [ :int, :int ], :int
  attach_function :aw_cav_change, [  ], :int
  attach_function :aw_cav_delete, [  ], :int
  attach_function :aw_world_cav_request, [ :int, :int ], :int
  attach_function :aw_world_cav_change, [  ], :int
  attach_function :aw_world_cav_delete, [  ], :int
  attach_function :aw_license_add, [  ], :int
  attach_function :aw_license_attributes, [ :string ], :int
  attach_function :aw_license_change, [  ], :int
  attach_function :aw_license_delete, [ :string ], :int
  attach_function :aw_license_next, [  ], :int
  attach_function :aw_license_previous, [  ], :int
  attach_function :aw_world_list, [  ], :int
  attach_function :aw_object_add, [  ], :int
  attach_function :aw_object_change, [  ], :int
  attach_function :aw_object_delete, [  ], :int
  attach_function :aw_object_load, [  ], :int
  attach_function :aw_object_query, [  ], :int
  # attach_function :aw_query, [ :int, :int, [[:int, 3], 3] ], :int
  # attach_function :aw_query_5x5, [ :int, :int, [[:int, 5], 5] ], :int
  attach_function :aw_random, [  ], :int
  attach_function :aw_world_attributes_change, [  ], :int
  attach_function :aw_universe_attributes_change, [  ], :int
  attach_function :aw_session, [  ], :int
  attach_function :aw_world_eject, [  ], :int
  attach_function :aw_sector_from_cell, [ :int ], :int
  attach_function :aw_universe_ejection_add, [  ], :int
  attach_function :aw_universe_ejection_delete, [ :int ], :int
  attach_function :aw_universe_ejection_lookup, [  ], :int
  attach_function :aw_universe_ejection_next, [  ], :int
  attach_function :aw_universe_ejection_previous, [  ], :int
  attach_function :aw_object_click, [  ], :int
  attach_function :aw_object_select, [  ], :int
  attach_function :aw_avatar_click, [ :int ], :int
  attach_function :aw_address, [ :int ], :int
  attach_function :aw_url_send, [ :int, :string, :string ], :int
  attach_function :aw_url_click, [ :string ], :int
  attach_function :aw_teleport, [ :int ], :int
  attach_function :aw_world_ejection_add, [  ], :int
  attach_function :aw_world_ejection_delete, [  ], :int
  attach_function :aw_world_ejection_lookup, [  ], :int
  attach_function :aw_world_ejection_next, [  ], :int
  attach_function :aw_world_ejection_previous, [  ], :int
  attach_function :aw_world_attribute_set, [ :int, :string ], :int
  attach_function :aw_world_attribute_get, [ :int, :pointer, :string ], :int
  attach_function :aw_delete_all_objects, [  ], :int
  attach_function :aw_cell_next, [  ], :int
  attach_function :aw_world_reload_registry, [  ], :int
  attach_function :aw_world_attributes_reset, [  ], :int
  attach_function :aw_terrain_set, [ :int, :int, :int, :int, :pointer ], :int
  attach_function :aw_terrain_query, [ :int, :int, :ulong ], :int
  attach_function :aw_terrain_next, [  ], :int
  attach_function :aw_terrain_delete_all, [  ], :int
  attach_function :aw_terrain_load_node, [  ], :int
  attach_function :aw_console_message, [ :int ], :int
  attach_function :aw_user_data_set, [ :pointer ], :int
  attach_function :aw_user_data, [  ], :pointer
  attach_function :aw_avatar_set, [ :int ], :int
  attach_function :aw_avatar_reload, [ :int, :int ], :int
  attach_function :aw_avatar_location, [ :int, :int, :string ], :int
  attach_function :aw_world_instance_set, [ :int, :int ], :int
  attach_function :aw_world_instance_get, [ :int ], :int
  attach_function :aw_botgram_send, [  ], :int
  attach_function :aw_toolbar_click, [  ], :int
  attach_function :aw_user_list, [  ], :int
  attach_function :aw_noise, [ :int ], :int
  attach_function :aw_world_attributes_send, [ :int ], :int
  attach_function :aw_camera_set, [ :int ], :int
  attach_function :aw_botmenu_send, [  ], :int
  attach_function :aw_object_bump, [  ], :int
  attach_function :aw_mover_set_state, [ :int, :int, :int ], :int
  attach_function :aw_mover_set_position, [ :int, :int, :int, :int, :int, :int, :int ], :int
  attach_function :aw_mover_rider_add, [ :int, :int, :int, :int, :int, :int, :int ], :int
  attach_function :aw_mover_rider_change, [ :int, :int, :int, :int, :int, :int, :int ], :int
  attach_function :aw_mover_rider_delete, [ :int, :int ], :int
  attach_function :aw_mover_links, [ :int ], :int
  attach_function :aw_object_zone_set, [ AwTypeVector, :uchar, :char, :float, :float, :ushort, :ulong, :ushort, :ushort, :string, :string, :string, :string, :string, :string ], :int
  attach_function :aw_object_zone, [ :pointer ], :pointer
  attach_function :aw_object_particles_set, [ AwTypeVectorRange, AwTypeVectorRange, AwTypeVectorRange, AwTypeVectorRange, AwTypeVectorRange, AwTypeVectorRange, :ulong, :ulong, :ushort, :ulong, :ulong, :ulong, :ulong, :ulong, :ulong, :float, :uchar, :ushort, :uchar, :string, :string ], :int
  attach_function :aw_object_particles, [ :pointer ], :pointer
  attach_function :aw_object_camera_set, [ :ushort, :float, :string ], :int
  attach_function :aw_object_camera, [ :pointer ], :pointer
  attach_function :aw_object_mover_set, [ :uchar, :ushort, :short, :short, :short, :short, :short, :char, :uchar, :uchar, :char, :char, :uchar, :uchar, :string, :string, :string, :string, :ushort, :pointer, :string ], :int
  attach_function :aw_object_mover, [ :pointer ], :pointer
  attach_function :aw_hud_create, [  ], :int
  attach_function :aw_hud_click, [  ], :int
  attach_function :aw_hud_destroy, [ :int, :int ], :int
  attach_function :aw_hud_clear, [ :int ], :int
  attach_function :aw_tick, [  ], :uint
  attach_function :aw_check_right, [ :int, :string ], :int
  attach_function :aw_check_right_all, [ :string ], :int
  attach_function :aw_has_world_right, [ :int, :int ], :int
  attach_function :aw_has_world_right_all, [ :int ], :int
  attach_function :aw_traffic_count, [ :pointer, :pointer ], :int
  attach_function :aw_zip, [ :pointer, :pointer, :pointer, :uint ], :int
  attach_function :aw_unzip, [ :pointer, :pointer, :pointer, :uint ], :int
  attach_function :aw_server_admin, [ :string, :int, :string, :pointer ], :int
  attach_function :aw_server_world_add, [  ], :int
  attach_function :aw_server_world_delete, [ :int ], :int
  attach_function :aw_server_world_change, [ :int ], :int
  attach_function :aw_server_world_list, [  ], :int
  attach_function :aw_server_world_start, [ :int ], :int
  attach_function :aw_server_world_stop, [ :int ], :int
  attach_function :aw_server_world_set, [ :int ], :int
  attach_function :aw_server_world_instance_set, [ :int ], :int
  attach_function :aw_server_world_instance_add, [ :int, :int ], :int
  attach_function :aw_server_world_instance_delete, [ :int, :int ], :int
  # attach_function :aw_contact_add, [ :int, :uint ], :int
  # attach_function :aw_contact_add_by_name, [ :string, :uint ], :int
  # attach_function :aw_contact_change, [ :int, :uint ], :int
  # attach_function :aw_contact_confirm, [ :int, :uint ], :int
  # attach_function :aw_contact_delete, [ :int ], :int
  # attach_function :aw_contact_list, [ :int ], :int
  # attach_function :aw_afk_set, [ :int ], :int
  # attach_function :aw_telegram_send, [ :string, :string ], :int
  # attach_function :aw_join, [ :int ], :int
  # attach_function :aw_join_reply, [ :int, :int ], :int
  # attach_function :aw_password_send, [  ], :int
  # attach_function :aw_immigrate, [  ], :int
  # attach_function :aw_register, [ :int ], :int
  # attach_function :aw_send_file, [  ], :int
  # attach_function :aw_send_file_reply, [ :int ], :int
  # attach_function :aw_login_timeout_set, [ :int ], :void
  # attach_function :aw_tunnel_set, [ :string, :ushort ], :int
  # attach_function :aw_tunnel_set_resolved, [ :ulong, :ushort ], :int
  # attach_function :aw_proxy_set, [ :string, :ushort ], :int
  # attach_function :aw_proxy_set_resolved, [ :ulong, :ushort ], :int
  # attach_function :aw_proxy_set_login, [ :string, :string ], :int
  # attach_function :aw_connection, [  ], :int
  # attach_function :aw_connection_set, [ :int ], :int
  # attach_function :aw_connection_state, [ :pointer ], :int
  # attach_function :aw_voip_data, [ :pointer, :uint ], :int
  # attach_function :aw_voip_group_set, [ :int, :string ], :int
  # attach_function :aw_debug_callback_set, [ callback([ :string ], :void) ], :int

  callback :handle_aw_callback, [:int], :void
  callback :handle_aw_event, [], :void
  attach_function :aw_callback_set, [:int, :handle_aw_callback], :int
  attach_function :aw_event_set, [:int, :handle_aw_event], :int
  attach_function :aw_instance_callback_set, [:int, :handle_aw_callback], :int
  attach_function :aw_instance_event_set, [:int, :handle_aw_event], :int
  attach_function :aw_data, [:int, :buffer_out], :pointer
  attach_function :aw_user_data_set, [:buffer_inout], :int
  # these take as the pointer a int[3][3] or int[5][5] respectively
  attach_function :aw_query, [:int, :int, :buffer_inout], :int
  attach_function :aw_query_5x5, [:int, :int, :buffer_inout], :int
  attach_function :aw_world_attribute_set, [:int, :buffer_in], :int
  attach_function :aw_world_attribute_get, [:int, :buffer_out, :buffer_out], :int
  
  alias :aw_string_set_ffi :aw_string_set
  alias :aw_data_set_ffi   :aw_data_set  
  alias :aw_bool_set_ffi   :aw_bool_set
  alias :aw_bool_ffi       :aw_bool

  def aw_bool_set(attribute, tf)
    aw_bool_set_ffi(attribute, tf ? 1 : 0)
  end

  def aw_bool(attribute)
    aw_bool_ffi(attribute) == 1 ? true : false
  end

  def aw_string_set(aw_attr,str,length=AW_MAX_ATTRIBUTE_LENGTH)
    aw_string_set_ffi(aw_attr,str[0,length])
  end

  def aw_data_set(aw_attr,data_buffer,length=AW_MAX_DATA_ATTRIBUTE_LENGTH)
    base_aw_data_set(aw_attr,data_buffer[0,length],
      length > AW_MAX_DATA_ATTRIBUTE_LENGTH ? AW_MAX_DATA_ATTRIBUTE_LENGTH : length )
  end
  
end
